### ISSUE TITLE
Error on RM3500ZB Update

### ISSUE THREAD

**Issue by vrouleau** [claudegel/sinope-130#120]
Installed a new RM3500ZB. No entities is added. Turned on debug traces. It does seem to read valid values from the device but fails on updating the 'switch' data. Here are the startup logs:

2022-12-10 15:55:28.146 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration meross_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-10 15:55:28.149 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-10 15:55:28.151 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration neviweb130 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-10 15:55:28.153 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration ui_lovelace_minimalist which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-10 15:55:28.156 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-10 15:55:28.158 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-10 15:55:40.544 DEBUG (SyncWorker_2) [custom_components.neviweb130] Login response: {}
2022-12-10 15:55:40.545 DEBUG (SyncWorker_2) [custom_components.neviweb130] Successfully logged in to: 14594
2022-12-10 15:55:40.816 DEBUG (SyncWorker_2) [custom_components.neviweb130] Number of networks found on Neviweb: 1
2022-12-10 15:55:40.827 DEBUG (SyncWorker_2) [custom_components.neviweb130] networks: [{'id': 15944, 'account$id': 14594, 'location$id': None, 'group$id': None, 'name': 'Maison', 'postalCode': 'H7N5W8', 'address': None, 'mode': 'home', 'icon': 1, 'type': None, 'kwhCost': 0.0885, 'deviceListUpdate': '2022-12-10 19:30:25', 'modified': '2022-01-22 14:11:53', 'created': '2019-11-14 01:06:53'}]
2022-12-10 15:55:40.827 DEBUG (SyncWorker_2) [custom_components.neviweb130] Selecting Maison network among: [{'id': 15944, 'account$id': 14594, 'location$id': None, 'group$id': None, 'name': 'Maison', 'postalCode': 'H7N5W8', 'address': None, 'mode': 'home', 'icon': 1, 'type': None, 'kwhCost': 0.0885, 'deviceListUpdate': '2022-12-10 19:30:25', 'modified': '2022-01-22 14:11:53', 'created': '2019-11-14 01:06:53'}]
2022-12-10 15:55:41.086 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received gateway data: [{'id': 141140, 'identifier': 'ccccccfffe6fb607', 'name': 'GT130', 'family': 'GT130', 'signature': {'model': 130, 'modelCfg': 1, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 3, 'minor': 0}, 'hardRev': 3}, 'location$id': 15944, 'parentDevice$id': None, 'group$id': 15139, 'orderIdx': 0, 'sku': 'GT130', 'vendor': 'Sinopé', 'url_en': 'https://www.sinopetech.com/produit/passerelle-zigbee/', 'url_fr': 'https://www.sinopetech.com/en/product/gateway-zigbee/'}, {'id': 350516, 'identifier': 'ccccccfffe6fb607-003c84fffe8b2211', 'name': 'RM3500ZB', 'family': '2151', 'signature': {'model': 2151, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 3, 'middle': 2, 'major': 0}, 'hardRev': 0}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 14416, 'orderIdx': 0, 'sku': 'RM3500ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 141145, 'identifier': 'ccccccfffe6fb607-500b914000022d16', 'name': 'TH1123ZB', 'family': '1123', 'signature': {'model': 1123, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 2}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 16675, 'orderIdx': 0, 'sku': 'TH1123ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 141141, 'identifier': 'ccccccfffe6fb607-500b91400001106c', 'name': 'TH1124ZB', 'family': '1124', 'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 14409, 'orderIdx': 0, 'sku': 'TH1124ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 141143, 'identifier': 'ccccccfffe6fb607-500b914000010fce', 'name': 'TH1124ZB', 'family': '1124', 'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 14413, 'orderIdx': 0, 'sku': 'TH1124ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 141144, 'identifier': 'ccccccfffe6fb607-500b914000011361', 'name': 'TH1124ZB', 'family': '1124', 'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 14411, 'orderIdx': 0, 'sku': 'TH1124ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 141146, 'identifier': 'ccccccfffe6fb607-500b91400001155d', 'name': 'TH1124ZB', 'family': '1124', 'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 15138, 'orderIdx': 0, 'sku': 'TH1124ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 211954, 'identifier': 'ccccccfffe6fb607-500b914000011225', 'name': 'TH1124ZB', 'family': '1124', 'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 15139, 'orderIdx': 0, 'sku': 'TH1124ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 141147, 'identifier': 'ccccccfffe6fb607-500b914000020ad1', 'name': 'TH1300ZB', 'family': '737', 'signature': {'model': 737, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 9, 'middle': 1, 'major': 1}, 'hardRev': 0}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 14416, 'orderIdx': 0, 'sku': 'TH1300ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}]
2022-12-10 15:55:41.522 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 130, 'modelCfg': 1, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 3, 'minor': 0}, 'hardRev': 3, 'protocol': 'sinopcom'}}
2022-12-10 15:55:41.730 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 2151, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 3, 'middle': 2, 'major': 0}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2022-12-10 15:55:42.049 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 1123, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 2, 'protocol': 'sinopcom'}}
2022-12-10 15:55:42.344 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1, 'protocol': 'sinopcom'}}
2022-12-10 15:55:42.538 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1, 'protocol': 'sinopcom'}}
2022-12-10 15:55:42.837 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1, 'protocol': 'sinopcom'}}
2022-12-10 15:55:43.063 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1, 'protocol': 'sinopcom'}}
2022-12-10 15:55:43.294 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1, 'protocol': 'sinopcom'}}
2022-12-10 15:55:43.489 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 737, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 9, 'middle': 1, 'major': 1}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2022-12-10 15:55:43.490 DEBUG (SyncWorker_2) [custom_components.neviweb130] Setting scan interval to: 0:06:00
2022-12-10 15:55:43.500 DEBUG (SyncWorker_2) [custom_components.neviweb130] Setting Homekit mode to: False
2022-12-10 15:55:43.691 DEBUG (MainThread) [custom_components.neviweb130.switch] Setting up neviweb130 switch RM3500ZB: {'id': 350516, 'identifier': 'ccccccfffe6fb607-003c84fffe8b2211', 'name': 'RM3500ZB', 'family': '2151', 'signature': {'model': 2151, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 3, 'middle': 2, 'major': 0}, 'hardRev': 0, 'protocol': 'sinopcom'}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 14416, 'orderIdx': 0, 'sku': 'RM3500ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}
2022-12-10 15:55:43.693 DEBUG (MainThread) [custom_components.neviweb130.sensor] Setting up neviweb130 sensor GT130: {'id': 141140, 'identifier': 'ccccccfffe6fb607', 'name': 'GT130', 'family': 'GT130', 'signature': {'model': 130, 'modelCfg': 1, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 3, 'minor': 0}, 'hardRev': 3, 'protocol': 'sinopcom'}, 'location$id': 15944, 'parentDevice$id': None, 'group$id': 15139, 'orderIdx': 0, 'sku': 'GT130', 'vendor': 'Sinopé', 'url_en': 'https://www.sinopetech.com/produit/passerelle-zigbee/', 'url_fr': 'https://www.sinopetech.com/en/product/gateway-zigbee/'}
2022-12-10 15:55:44.122 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1123ZB: {'id': 141145, 'identifier': 'ccccccfffe6fb607-500b914000022d16', 'name': 'TH1123ZB', 'family': '1123', 'signature': {'model': 1123, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 2, 'protocol': 'sinopcom'}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 16675, 'orderIdx': 0, 'sku': 'TH1123ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}
2022-12-10 15:55:44.122 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1124ZB: {'id': 141141, 'identifier': 'ccccccfffe6fb607-500b91400001106c', 'name': 'TH1124ZB', 'family': '1124', 'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1, 'protocol': 'sinopcom'}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 14409, 'orderIdx': 0, 'sku': 'TH1124ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}
2022-12-10 15:55:44.123 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1124ZB: {'id': 141143, 'identifier': 'ccccccfffe6fb607-500b914000010fce', 'name': 'TH1124ZB', 'family': '1124', 'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1, 'protocol': 'sinopcom'}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 14413, 'orderIdx': 0, 'sku': 'TH1124ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}
2022-12-10 15:55:44.123 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1124ZB: {'id': 141144, 'identifier': 'ccccccfffe6fb607-500b914000011361', 'name': 'TH1124ZB', 'family': '1124', 'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1, 'protocol': 'sinopcom'}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 14411, 'orderIdx': 0, 'sku': 'TH1124ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}
2022-12-10 15:55:44.123 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1124ZB: {'id': 141146, 'identifier': 'ccccccfffe6fb607-500b91400001155d', 'name': 'TH1124ZB', 'family': '1124', 'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1, 'protocol': 'sinopcom'}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 15138, 'orderIdx': 0, 'sku': 'TH1124ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}
2022-12-10 15:55:44.123 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1124ZB: {'id': 211954, 'identifier': 'ccccccfffe6fb607-500b914000011225', 'name': 'TH1124ZB', 'family': '1124', 'signature': {'model': 1124, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 1, 'protocol': 'sinopcom'}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 15139, 'orderIdx': 0, 'sku': 'TH1124ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}
2022-12-10 15:55:44.123 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1300ZB: {'id': 141147, 'identifier': 'ccccccfffe6fb607-500b914000020ad1', 'name': 'TH1300ZB', 'family': '737', 'signature': {'model': 737, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 9, 'middle': 1, 'major': 1}, 'hardRev': 0, 'protocol': 'sinopcom'}, 'location$id': 15944, 'parentDevice$id': 141140, 'group$id': 14416, 'orderIdx': 0, 'sku': 'TH1300ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}
2022-12-10 15:55:44.229 DEBUG (SyncWorker_0) [custom_components.neviweb130] Received devices status: {'status': 'online'}
2022-12-10 15:55:44.229 DEBUG (SyncWorker_0) [custom_components.neviweb130.sensor] Updating neviweb130 sensor GT130 (0.186 sec): {'status': 'online'}
2022-12-10 15:55:44.885 DEBUG (SyncWorker_7) [custom_components.neviweb130.switch] Updating neviweb130 switch RM3500ZB (0.845 sec): {'onOff': 'on', 'waterLeakStatus': 'ok', 'roomTemperature': 55.05, 'errorCodeSet1': {'temperature': 'ok', 'stm_mcu': 'ok'}, 'loadConnected': 4349, 'coldLoadPickupStatus': 1, 'rssi': -68, 'tankSize': 60}
2022-12-10 15:55:45.186 ERROR (MainThread) [homeassistant.components.switch] neviweb130: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
    await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb130/switch.py", line 667, in update
    self._relayK1 = device_data[ATTR_ERROR_CODE_SET1]["relayK1"]
KeyError: 'relayK1'

**Comment by claudegel** [comment]
Your faster then me :) I just installed my RM3500ZB but started first by adding support for ZHA. Tonight I'll switch my RM3500ZB from ZHA to GT130 and finalise the support this weekend.

**Comment by claudegel** [comment]
Ok I've created a branch
https://github.com/claudegel/sinope-130/tree/calypso-support
Should work perfectly. Please upload file switch.py and const.py and test

**Comment by claudegel** [comment]
5 minutes after HA restart, the energy stats are populated and updated every 30 minutes. Just update to neviweb130 1.9.0

**Comment by vrouleau** [comment]
Works now. Thanks
