### ISSUE TITLE
Probleme de mise a jour sur thermostat

### ISSUE THREAD

**Issue by niighthawk** [claudegel/sinope-130#128]
Bonjour Claude, quand je redémarre mon HA tout fonctionne bien, depassé le delais de 320secondes, le thermostat à chaque manipulation m'envois ces erreurs. 

Logger: homeassistant.helpers.entity
Source: custom_components/neviweb130/climate.py:989
Integration: Sinope Neviweb130 (documentation)
First occurred: 17:14:12 (1 occurrences)
Last logged: 17:14:12

Update for climate.neviweb130_climate_th1123wf fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb130/climate.py", line 989, in update
    self._hour_energy_kwh_count = device_hourly_stats[1]["counter"] / 1000
IndexError: list index out of range

- Si je fait des moficiation Via NEVIWEB, la carte thermostat sur HA ne se met pas à jour elle affiche une incrémentation en haut à gauche comme quoi elle ne s'est pas mis à jour depuis le dernier redémarrage, 

- Si je joue avec le pré-réglage PRÉSENT - ABSENT automatiquement il se remet à Présent, meme si mon profile dans neiweb est mis à Absent.

- Si je modifie la température manuellement sur le thermostat, la carte Thermostat  sur HA ne se met pas à jour

des idées de ce qui peux causer tous ces petits bug ? 

Merci et bon temps des fêtes !

**Comment by claudegel** [comment]
Bonjour, Quel est le model de thermostat. Il semble bloquer sur la recherche des statistiques d'énergie et dans ce cas la mise a jour ne se fait pas pour cet appareil.
On va donc valider si le thermostat suporte les statistiques

**Comment by claudegel** [comment]
Si vous pouvez editer le code dans climate.py, ajoutez ceci avant la ligne 989
_LOGGER.debug("Energy data for %s = %s", self._sku, device_hourly_stats)
Redémarrez HA et vérifier les log pour retrouver cette ligne Energy data for TH1123WF
je suis pas 100% certain mais je pense que les thermostats wifi n'ont pas de statistique d'énergie. Si c'est le cas on va les exclure de cette section.

**Comment by niighthawk** [comment]
TH11123wf

**Comment by niighthawk** [comment]
Comme ceci ?


![Adobe Dreamweaver CS6 -  climate py](https://user-images.githubusercontent.com/30214804/209416424-759bfb03-aa01-473e-b4fd-007fb74c1bd9.jpg)

**Comment by niighthawk** [comment]
Maintenant j'ai cec comme erreur au démarrage et la carte thermostat ne fonctionne plus

![Paramètres – Home Assistant — Mozilla Firefox](https://user-images.githubusercontent.com/30214804/209416673-2f5b7054-702b-41d3-b769-918c958fe013.jpg)

**Comment by claudegel** [comment]
Il semble que ton fichier climate.py est introuvable. Avec quoi tu l'as édité

**Comment by claudegel** [comment]
pour ton ecriture il faut ajouter 4 espaces devant ta ligne elle doit être indentée comme la ligne du dessous, self..... C'est probablement pour ca que ca plante

**Comment by niighthawk** [comment]
javais modifier avec dreamweaver mais jai recommancé avec plugin direct dans HA et la ca fonctionne il la bien prit

![Studio Code Server – Home Assistant — Mozilla Firefox](https://user-images.githubusercontent.com/30214804/209417059-c5a08a8b-4c7a-4c1d-9d61-158f3b2a30cf.jpg)

 sauf maintenant j'ai cette erreur ca te parle ? 
![Paramètres – Home Assistant — Mozilla Firefox_2](https://user-images.githubusercontent.com/30214804/209417064-9668a7af-b304-44ab-92c8-b48a5d8b5f0d.jpg)

**Comment by niighthawk** [comment]
En passant un gros merci de m'aider un 23 dec au soir :) très apprécié 👍

**Comment by niighthawk** [comment]
là ils semble ne plus y avoir de message d'erreur parcontre il reste tjrs le fait que si je modifie physiquement la température à la main sur le thermostat, la carte sur HA ne se met pas à jour, meme chose si je met NEVIWEB à une valeur X, la donnée n'est pas mis à jour sur HA

**Comment by claudegel** [comment]
Ca me dit rien à moins qu'il y a une erreur dans la ligne que tu as ajouté
assure-toi que devant ta ligne ce ne sont que des espace pas de tab

**Comment by niighthawk** [comment]
là ils semble ne plus y avoir de message d'erreur parcontre il reste tjrs le fait que si je modifie physiquement la température à la main sur le thermostat, la carte sur HA ne se met pas à jour, meme chose si je met NEVIWEB à une valeur X, la donnée n'est pas mis à jour sur HA.

à l'inverse si je modifie sur HA la donnée X est poussé automatiquement sur le thermostat et sur NeviWeblà ils semble ne plus y avoir de message d'erreur parcontre il reste tjrs le fait que si je modifie physiquement la température à la main sur le thermostat, la carte sur HA ne se met pas à jour, meme chose si je met NEVIWEB à une valeur X, la donnée n'est pas mis à jour sur HA.

à l'inverse si je modifie sur HA la donnée X est poussé automatiquement sur le thermostat et sur NeviWeb

**Comment by claudegel** [comment]
Quand tu modifis le setpoint manuellement sur ton thermostat ca ne va pas sur HA. Il faut attendre le délais de scan_interval pour que HA se mette a jour. meme chose si tu modifis le setpoint sur Neviweb il faut attendre le délais de HA. 
HA fait du polling aux 5 minutes sur neviweb pour avoir les changements.

Est-ce que tu as des valeurs dans tes log pour Energy data for.....

**Comment by claudegel** [comment]
la patch ne produit pas d'erreur ici

**Comment by claudegel** [comment]
il me faut les valeur que donne Energy data for....

**Comment by niighthawk** [comment]
jai pu aucun code d’erreur dans mes log, dois-je activer autre chose pour que puisse te donner l'information demandé du energy data ?


le poll est a 320 le minimum qu'on peut mettre ces 300 ? ok alors ma testé cela merci encore

**Comment by claudegel** [comment]
Les stats prennent 5 minutes a démarrer après un reboot de HA. check tes log et a devrait apparaitre. Recherche une ligne qui contient Energy data for....

**Comment by claudegel** [comment]
est-ce que tu vois tes thermostats

**Comment by claudegel** [comment]
je vois que les stats sont à 0 donc il y a eu un update. dans dans le fichier home-assistant.log il doit y avoir un message pour Energy data for....

**Comment by niighthawk** [comment]
non j'ai été voir aucune ligne ne mentionne "Energy data for" dans home-assistant.log

**Comment by claudegel** [comment]
Dans Neviweb est-ce qu'il y a des statistiques de consommation d'énergie pour ces thermostats wifi

**Comment by claudegel** [comment]
est ce que tu as encore des erreurs IndexError: list index out of range comme au début ?
sinon réinstalle neviweb130 vi hacs et redémarre HA pour voir si les ereurs reviennent. Des fois Sinopé brasse son code et ca bloque temporairement.

**Comment by niighthawk** [comment]
à date tout fonctionne bien quand on comprend que ca update au 5min notre Carte HA et la modification tu ma fais rajouté dans climate.py

Dans nevi je vois ca, est-ceque c'estca tu me parle ? 
![Neviweb — Mozilla Firefox](https://user-images.githubusercontent.com/30214804/209418608-d3ceea05-4479-4417-88a3-ab9ab904a280.jpg)

**Comment by niighthawk** [comment]
d'apres moi  ce n'est pas fonctionnelle car on y voit la mention * NA DATA NOT AVAILABLE

**Comment by claudegel** [comment]
![stat](https://user-images.githubusercontent.com/4268938/209418802-bc28b573-d326-41c6-af46-6254e129afac.jpg)
moi j'ai ceci. toi tu as juste la température donc pour le wifi il n'y a pas de valeur pour l'énergie

**Comment by claudegel** [comment]
je vais donc mettre une exception pour pas executer  le code de stat pour les thermostats wifi

**Comment by claudegel** [comment]
prends ta ligne _LOGGER et remonte la au dessus de la la ligne comme sur l'image ci dessous
![stat1](https://user-images.githubusercontent.com/4268938/209418929-09b7a8c6-a991-4034-af7e-2f57e3911daf.jpg)
ca devrait donner du data dans les log même si neviweb envoi rien

**Comment by niighthawk** [comment]
c'est fait, donc j'attend 5 minutes pour voir s'il y a ENERGY DATA FOR dans mon fichier de log ?

**Comment by claudegel** [comment]
oui 5 - 10 minutes

**Comment by niighthawk** [comment]
après 10min toujours aucune ligne Energy data for

**Comment by claudegel** [comment]
tu as bien mi la ligne juste en dessous de device_hourly_stats =... ?

**Comment by sicarriere** [comment]
Juste vous dire que j'ai les mêmes thermostat, mais je n'ai aucun problème. Mais je suis à HA 2022.12.7 et nevieweb à 1.9.0 je pourrais updaté demain pour voir de mon côté.

**Comment by claudegel** [comment]
OK peut-être que Sinopé a fait une modification et que ca a foutu le bordel pour qualques minutes. met a jour HA et neviweb130 et ajoute la ligne de _LOGGER et on verra.
Valide de temps en temps si il y a du data energy dans neviweb ou bien si il y a juste la température. Au moins tu es pas pogné dans la tempête :)

**Comment by niighthawk** [comment]
je suis a ha 2022.12.8 et 9.4

**Comment by niighthawk** [comment]
et ton addon 1.9.1 je crois ( le dernier )

**Comment by claudegel** [comment]
oui j'attends de voir si on doit corriger quelques chose avant de sortir 1.9.2

**Comment by claudegel** [comment]
oublis pas de remettre la ligne de _LOGGER dans climate.py

**Comment by sicarriere** [comment]
Voici chez nous avec HA 2022.12.8 et Neviweb-130 à 1.9.1 :
`
2022-12-24 09:07:40.866 DEBUG (SyncWorker_8) [custom_components.neviweb130.climate] Updating neviweb130 climate Salon (0.933 sec): {'roomSetpoint': 21, 'outputPercentDisplay': {'percent': 100, 'sourceType': 'heating'}, 'roomTemperature': {'value': 19.56, 'error': None}, 'roomSetpointMin': 5, 'roomSetpointMax': 30, 'roomTemperatureDisplay': {'value': 19.5, 'status': 'on'}, 'timeFormat': '24h', 'temperatureFormat': 'celsius', 'drStatus': {'drActive': 'off', 'optOut': 'off', 'setpoint': 'off', 'powerAbsolute': 'off', 'powerRelative': 'off'}, 'drSetpoint': {'status': 'off', 'value': None}, 'loadWattOutput1': 1869, 'loadWatt': 1869, 'wifiRssi': -48, 'keyboardLock': 'unlock', 'config2ndDisplay': 'default', 'setpointMode': 'manual', 'occupancyMode': 'none', 'backlightAutoDim': 'alwaysOn', 'earlyStartCfg': 'off', 'roomSetpointAway': 15}

2022-12-24 09:07:40.969 DEBUG (SyncWorker_8) [custom_components.neviweb130.climate] Energy data for TH1123WF = [{'period': 0, 'periodQuality': 0, 'counter': 6188580, 'counterDate': '2022-12-24T08:01:22-05:00', 'date': '2022-12-24T08:00:00-05:00'}, {'period': 1870, 'periodQuality': 60, 'counter': 6186710, 'counterDate': '2022-12-24T07:01:21-05:00', 'date': '2022-12-24T07:00:00-05:00'}, {'period': 1687, 'periodQuality': 60, 'counter': 6185023, 'counterDate': '2022-12-24T06:01:22-05:00', 'date': '2022-12-24T06:00:00-05:00'}, {'period': 1305, 'periodQuality': 60, 'counter': 6183718, 'counterDate': '2022-12-24T05:01:20-05:00', 'date': '2022-12-24T05:00:00-05:00'}, {'period': 1155, 'periodQuality': 60, 'counter': 6182563, 'counterDate': '2022-12-24T04:01:17-05:00', 'date': '2022-12-24T04:00:00-05:00'}, {'period': 833, 'periodQuality': 60, 'counter': 6181730, 'counterDate': '2022-12-24T03:01:18-05:00', 'date': '2022-12-24T03:00:00-05:00'}, {'period': 221, 'periodQuality': 60, 'counter': 6181509, 'counterDate': '2022-12-24T02:01:18-05:00', 'date': '2022-12-24T02:00:00-05:00'}, {'period': 0, 'periodQuality': 60, 'counter': 6181509, 'counterDate': '2022-12-24T01:01:20-05:00', 'date': '2022-12-24T01:00:00-05:00'}, {'period': 0, 'periodQuality': 60, 'counter': 6181509, 'counterDate': '2022-12-24T00:01:23-05:00', 'date': '2022-12-24T00:00:00-05:00'}, {'period': 0, 'periodQuality': 60, 'counter': 6181509, 'counterDate': '2022-12-23T23:01:26-05:00', 'date': '2022-12-23T23:00:00-05:00'}, {'period': 1447, 'periodQuality': 60, 'counter': 6180062, 'counterDate': '2022-12-23T22:01:27-05:00', 'date': '2022-12-23T22:00:00-05:00'}, {'period': 0, 'periodQuality': 60, 'counter': 6180062, 'counterDate': '2022-12-23T21:01:29-05:00', 'date': '2022-12-23T21:00:00-05:00'}, {'period': 0, 'periodQuality': 60, 'counter': 6180062, 'counterDate': '2022-12-23T20:01:27-05:00', 'date': '2022-12-23T20:00:00-05:00'}, {'period': 52, 'periodQuality': 60, 'counter': 6180010, 'counterDate': '2022-12-23T19:01:23-05:00', 'date': '2022-12-23T19:00:00-05:00'}, {'period': 1868, 'periodQuality': 60, 'counter': 6178142, 'counterDate': '2022-12-23T18:01:25-05:00', 'date': '2022-12-23T18:00:00-05:00'}, {'period': 1870, 'periodQuality': 60, 'counter': 6176272, 'counterDate': '2022-12-23T17:01:24-05:00', 'date': '2022-12-23T17:00:00-05:00'}, {'period': 1082, 'periodQuality': 60, 'counter': 6175190, 'counterDate': '2022-12-23T16:01:24-05:00', 'date': '2022-12-23T16:00:00-05:00'}, {'period': 1307, 'periodQuality': 60, 'counter': 6173883, 'counterDate': '2022-12-23T15:01:22-05:00', 'date': '2022-12-23T15:00:00-05:00'}, {'period': 267, 'periodQuality': 60, 'counter': 6173616, 'counterDate': '2022-12-23T14:01:19-05:00', 'date': '2022-12-23T14:00:00-05:00'}, {'period': 51, 'periodQuality': 60, 'counter': 6173565, 'counterDate': '2022-12-23T13:01:21-05:00', 'date': '2022-12-23T13:00:00-05:00'}, {'period': 1009, 'periodQuality': 60, 'counter': 6172556, 'counterDate': '2022-12-23T12:01:19-05:00', 'date': '2022-12-23T12:00:00-05:00'}, {'period': 1844, 'periodQuality': 60, 'counter': 6170712, 'counterDate': '2022-12-23T11:01:22-05:00', 'date': '2022-12-23T11:00:00-05:00'}, {'period': 1866, 'periodQuality': 60, 'counter': 6168846, 'counterDate': '2022-12-23T10:01:27-05:00', 'date': '2022-12-23T10:00:00-05:00'}, {'period': 1870, 'periodQuality': 60, 'counter': 6166976, 'counterDate': '2022-12-23T09:01:26-05:00', 'date': '2022-12-23T09:00:00-05:00'}, {'period': 1867, 'periodQuality': 60, 'counter': 6165109, 'counterDate': '2022-12-23T08:01:29-05:00', 'date': '2022-12-23T08:00:00-05:00'}, {'period': 1871, 'periodQuality': 60, 'counter': 6163238, 'counterDate': '2022-12-23T07:01:26-05:00', 'date': '2022-12-23T07:00:00-05:00'}, {'period': 1427, 'periodQuality': 60, 'counter': 6161811, 'counterDate': '2022-12-23T06:01:30-05:00', 'date': '2022-12-23T06:00:00-05:00'}, {'period': 823, 'periodQuality': 60, 'counter': 6160988, 'counterDate': '2022-12-23T05:01:23-05:00', 'date': '2022-12-23T05:00:00-05:00'}, {'period': 608, 'periodQuality': 60, 'counter': 6160380, 'counterDate': '2022-12-23T04:01:35-05:00', 'date': '2022-12-23T04:00:00-05:00'}, {'period': 206, 'periodQuality': 60, 'counter': 6160174, 'counterDate': '2022-12-23T03:01:21-05:00', 'date': '2022-12-23T03:00:00-05:00'}, {'period': 0, 'periodQuality': 60, 'counter': 6160174, 'counterDate': '2022-12-23T02:01:21-05:00', 'date': '2022-12-23T02:00:00-05:00'}, {'period': 0, 'periodQuality': 60, 'counter': 6160174, 'counterDate': '2022-12-23T01:01:22-05:00', 'date': '2022-12-23T01:00:00-05:00'}, {'period': 0, 'periodQuality': 60, 'counter': 6160174, 'counterDate': '2022-12-23T00:01:23-05:00', 'date': '2022-12-23T00:00:00-05:00'}, {'period': 0, 'periodQuality': 60, 'counter': 6160174, 'counterDate': '2022-12-22T23:01:25-05:00', 'date': '2022-12-22T23:00:00-05:00'}, {'period': 1824, 'periodQuality': 60, 'counter': 6158350, 'counterDate': '2022-12-22T22:01:28-05:00', 'date': '2022-12-22T22:00:00-05:00'}, {'period': 1871, 'periodQuality': 60, 'counter': 6156479, 'counterDate': '2022-12-22T21:01:23-05:00', 'date': '2022-12-22T21:00:00-05:00'}, {'period': 1866, 'periodQuality': 60, 'counter': 6154613, 'counterDate': '2022-12-22T20:01:30-05:00', 'date': '2022-12-22T20:00:00-05:00'}, {'period': 1871, 'periodQuality': 60, 'counter': 6152742, 'counterDate': '2022-12-22T19:01:25-05:00', 'date': '2022-12-22T19:00:00-05:00'}, {'period': 1870, 'periodQuality': 60, 'counter': 6150872, 'counterDate': '2022-12-22T18:01:23-05:00', 'date': '2022-12-22T18:00:00-05:00'}, {'period': 1869, 'periodQuality': 60, 'counter': 6149003, 'counterDate': '2022-12-22T17:01:22-05:00', 'date': '2022-12-22T17:00:00-05:00'}, {'period': 1867, 'periodQuality': 60, 'counter': 6147136, 'counterDate': '2022-12-22T16:01:28-05:00', 'date': '2022-12-22T16:00:00-05:00'}, {'period': 1871, 'periodQuality': 60, 'counter': 6145265, 'counterDate': '2022-12-22T15:01:22-05:00', 'date': '2022-12-22T15:00:00-05:00'}, {'period': 1868, 'periodQuality': 60, 'counter': 6143397, 'counterDate': '2022-12-22T14:01:24-05:00', 'date': '2022-12-22T14:00:00-05:00'}, {'period': 1870, 'periodQuality': 60, 'counter': 6141527, 'counterDate': '2022-12-22T13:01:24-05:00', 'date': '2022-12-22T13:00:00-05:00'}, {'period': 1867, 'periodQuality': 60, 'counter': 6139660, 'counterDate': '2022-12-22T12:01:27-05:00', 'date': '2022-12-22T12:00:00-05:00'}, {'period': 1871, 'periodQuality': 60, 'counter': 6137789, 'counterDate': '2022-12-22T11:01:23-05:00', 'date': '2022-12-22T11:00:00-05:00'}, {'period': 1869, 'periodQuality': 60, 'counter': 6135920, 'counterDate': '2022-12-22T10:01:24-05:00', 'date': '2022-12-22T10:00:00-05:00'}, {'period': 1863, 'periodQuality': 60, 'counter': 6134057, 'counterDate': '2022-12-22T09:01:34-05:00', 'date': '2022-12-22T09:00:00-05:00'}]
`
Donc, en conclusion, ça fonctionne. Si tu veux que j'insère d'autres traces pour aider notre ami, juste à me le dire.

**Comment by claudegel** [comment]
Bien content. Ca veut dire que les wifi ont des statistiques de consommation. Il y a due y avoir une panne ou une modification sur Neviweb qui a planté ces thermostats. je vais voir si ils ont fait des mise a jour. Merci. Tu peux mettre un # en face de la ligne et si ça le refait alors enleve le # et regardes les log

Merci pour ton aide et Joyeux Noël

**Comment by sicarriere** [comment]
J'espère que pour @niighthawk ça fonctionne. Je sais qu'il a fermé le issue, mais n'a pas commenté pour nous dire si c'est revenu ok de son côté.

**Comment by niighthawk** [comment]
@sicarriere  hier j'ai pourtant écrit que tout fonctionnais bien de mon côté également et que je n'avais plus de bug, la seul chose je sais pas ou vous voyez l'information ENERGY DATA FOR car moi dans mon log ya 4-5 lignes gros max, alors p-e il faut j’active autre chose pour voir plus de log, mais bon, mis appart le fait que je ne vois pas ca, mon thermostat n'utilise pas cette fonction c'est pour ca que pour moi tout fonctionnais bien suivant nos discussion et correctif de Claude.

@claudegel  je viens de voir la version 1.9.2 sortir, devons nous remettre la ligne _logger ? ou dans la nouvelle version elle est déjà là ?

Merci à vous 2

**Comment by claudegel** [comment]
Pour voir les log plus en détail il faut les lignes suivantes dans configuration.yaml
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```
la ligne _LOGGER n'est pas dans la version 1.9.2 mais je vais la remettre dans la prochaine avec un # devant 
si besoin on enlève le # et ca va s'activer

**Comment by claudegel** [comment]
J'ai sorti 1.9.3 avec la ligne de debug en commentaire. Si jamais le bug revient on pourra trouver ce que Neviweb envoi
