### ISSUE TITLE
*Ouellet OTH3600-GA-GT Floor heating thermostat

### ISSUE THREAD

**Issue by canon102** [claudegel/sinope-130#20]
Hey There,

new to HAAS but rolling through it pretty good. 
Tried to add your Sinope-130 to my HAAS setup. 

I have a GT130, but i use the Ouellet OTH3600-GA-GT Floor heating thermostat.

When i added the code to the config.yaml file i get this error 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb130/__init__.py", line 41, in setup
    data = Neviweb130Data(hass_config[DOMAIN])
  File "/config/custom_components/neviweb130/__init__.py", line 64, in __init__
    self.neviweb130_client = Neviweb130Client(username, password, network)
  File "/config/custom_components/neviweb130/__init__.py", line 100, in __init__
    self.__get_gateway_data()
  File "/config/custom_components/neviweb130/__init__.py", line 175, in __get_gateway_data
    data = self.get_device_attributes(device["id"], [ATTR_SIGNATURE])
TypeError: string indices must be integers

Please Help

**Comment by charlesdagenais** [comment]
Can you see debug log? 

What is the output of raw_res.json() ?
 (Output by `LOGGER.debug("Received gateway data: %s", raw_res.json())` )

Add this to your configuration.yaml 
`logger:
  default: warning
  logs:
    custom_components.neviweb: debug `

**Comment by canon102** [comment]
In home assistant when i go into Config - Logs i see.

020-12-28 13:33:07 DEBUG (SyncWorker_2) [custom_components.neviweb130] Successfully logged in
2020-12-28 13:33:08 DEBUG (SyncWorker_2) [custom_components.neviweb130] Selecting GT130 network among: [{'id': 22557, 'location$id': None, 'group$id': None, 'name':IVE REDACTED THIS SECTION FOR PRIVACY', 'mode': 'home', 'icon': 1, 'type': None, 'kwhCost': 0.07, 'deviceListUpdate': '2020-12-17 08:27:14', 'modified': None, 'created': '2020-10-09 02:44:38'}]
2020-12-28 13:33:08 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received gateway data: {'error': {'code': 'VALINVLD', 'data': {'value': None, 'name': 'location$id'}}}
2020-12-28 13:33:09 ERROR (MainThread) [homeassistant.setup] Error during setup of component neviweb130
Traceback (most recent call last):

Is there something / somewhere else i should look?

**Comment by claudegel** [comment]
Hi, what did you put in configuration.yaml for the network. It should be the same as the name of your network that you have redacted. Also do you have other zigbee devices then the Ouellet OTH3600-GA-GT in Neviweb?
In your configuration.yaml change:
```
logger:
  default: warning
  logs:
    custom_components.neviweb: debug
```
add this
`custom_components.neviweb130: debug`
It look like you received no data for gateway data

**Comment by claudegel** [comment]
Also if you can connect to your Neviweb in your browser please open the debug console and select your thermostat. Then open the configuration and in the console look for :

`signature | Object { model: 737, modelCfg: 0, softBuildCfg: 0, … }`
This is my floor thermostat we need the model number for your thermostat to add it to the thermostat list in neviweb130

**Comment by claudegel** [comment]
Oups your OTH3600-GA-GT is not a zigbee or wifi device. it connect to Neviweb via GT125, not GT130
you should pick the other custom_component neviweb not neviweb130
If you have installed via HACS just pick the Sinope Neviweb
If you install via my git pick  claudegel /sinope-1 
both custom_components can coexist in HA

**Comment by canon102** [comment]
> Hi, what did you put in configuration.yaml for the network. It should be the same as the name of your network that you have redacted. Also do you have other zigbee devices then the Ouellet OTH3600-GA-GT in Neviweb?
> In your configuration.yaml change:
> 
> ```
> logger:
>   default: warning
>   logs:
>     custom_components.neviweb: debug
> ```
> 
> add this
> `custom_components.neviweb130: debug`
> It look like you received no data for gateway data

Thanks for the assistance, im a bit dumb so i'll try and give the most details i can. 

I have a OTH-3600-GA-ZB floor heat thermostat. Connected to the GT-130. 
GT130 connected via ethernet to my LAN network - Named "Lan"

my configuration.yaml has this listed. 

    # Example configuration.yaml entry
neviweb130:
  username: REDACTED@gmail.com
  password: REDACTED
  network: LAN
  scan_interval: 360

logger:
  default: warning
  logs:
    custom_components.neviweb130: debug


Log file contains this error. 

2020-12-28 18:33:28 DEBUG (SyncWorker_1) [custom_components.neviweb130] Login response: {'user': {'id': 19138, 'role': 'owner', 'email': 'Jsolta6@gmail.com', 'locale': 'en', 'format': {'time': '24', 'temperature': 'c'}, 'initialized': 1}, 'account': {'id': 19363, 'interface': 'neviweb', 'type': 'free'}, 'iat': 1609202008095, 'session': '77470cc4ab84a97e55dfc9cae71c7e916b15da107db96778', 'refreshToken': 'bf5ddcfc4697327fc8d3ca10b5018e6818c65eab717704ec4924ccf644d3e25eb44c208c41cf48a88aa04297399c3d1b'}
2020-12-28 18:33:28 DEBUG (SyncWorker_1) [custom_components.neviweb130] Successfully logged in
2020-12-28 18:33:28 DEBUG (SyncWorker_1) [custom_components.neviweb130] Selecting LAN network among: [{'id': 22557, 'location$id': None, 'group$id': None, 'name': 'XXREDACTED', 'postalCode': 'REDACTED', 'mode': 'home', 'icon': 1, 'type': None, 'kwhCost': 0.07, 'deviceListUpdate': '2020-12-17 08:27:14', 'modified': None, 'created': '2020-10-09 02:44:38'}]
2020-12-28 18:33:28 DEBUG (SyncWorker_1) [custom_components.neviweb130] Received gateway data: {'error': {'code': 'VALINVLD', 'data': {'value': None, 'name': 'location$id'}}}
2020-12-28 18:33:29 ERROR (MainThread) [homeassistant.setup] Error during setup of component neviweb130
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/neviweb130/__init__.py", line 41, in setup
data = Neviweb130Data(hass_config[DOMAIN])
File "/config/custom_components/neviweb130/__init__.py", line 64, in __init__
self.neviweb130_client = Neviweb130Client(username, password, network)
File "/config/custom_components/neviweb130/__init__.py", line 100, in __init__
self.__get_gateway_data()
File "/config/custom_components/neviweb130/__init__.py", line 175, in __get_gateway_data
data = self.get_device_attributes(device["id"], [ATTR_SIGNATURE])
TypeError: string indices must be integers

**Comment by claudegel** [comment]
Your network name parameter is not the name of your home lan. It is the name in Neviweb for your GT130 network
It should be the name you've redacted in your post above (XXREDACTED)
` 'name': 'XXREDACTED', 'postalCode': 'REDACTED',`
When I check for OTH3600-GA-GT on the net it is described as connect via GT125. Maybe they have a new version that connect to the GT130 ?
One thing you can try if you have only a GT130 connected to Neviweb, is to omit the network parameter in configuration.yaml
neviweb130 will pick your network name in the gateway data.

**Comment by claudegel** [comment]
Hi this is the documentation for Ouellet's thermostats compatible with Neviweb
```
    Zigbee
        OTH4000-ZB
        OTH3600-GA-ZB

    Mi-Wi
        OTH2750-GT
        OTH3600-GA-GT  <-----
        OTH4000-GT  
```
if your thermostat is a OTH3600-GA-GT, it is a mi-wi device that connect to GT125
for the GT130 it's  OTH3600-GA-ZB

**Comment by canon102** [comment]
Your network name parameter is not the name of your home lan. It is the name in Neviweb for your GT130 network
It should be the name you've redacted in your post above (XXREDACTED)
'name': 'XXREDACTED', 'postalCode': 'REDACTED',


This Was the answer right here !!!! 

Made the change, rebooted the server, and now my thermostat shows up as a entity. 

Thanks so much for the help.

**Comment by claudegel** [comment]
Ok great, now I'll need your help. Look in your HA log for line:
`...neviweb130] Received signature data: {'signature': {'model': 5051,<------`
I need the model # for your thermostat.
Do you have other Ouellet devices ou Sinope devices connected to Neviweb ?

**Comment by canon102** [comment]
not to hijackmy own thread here but im wondering if you can assist with another issue. 

It seems to me that i cannot connect to many devices from my computer that i can through the ios app. 

Example. I banged my head for hours trying to get my ip cams to show up on my pc dashboard. finally gave up. Went to bed, opened up the mobile dashboard and the ip cam was there. working properly. 

went back to pc.  card is on dashboard, but does not work on computer. - Works fine on IOS.

**Comment by canon102** [comment]
Not to hijack my own thread, but any idea why 

> `neviweb130] Received signature data: {'signature': {'model': 5051,<------`
> I need the model # for your thermostat.

2020-12-28 19:24:23 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate OTH3600-GA-ZB: {'id': 129826, 'identifier': '500b91400002079e', 'name': 'OTH3600-GA-ZB', 'family': '737', 'location$id': 22557, 'parentDevice$id': 129825, 'group$id': None, 'orderIdx': 0, 'sku': 'TH1300ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None, 'signature': {'model': 737, 'modelCfg': 2, 'softBuildCfg': 0, 'softVersion': {'minor': 2, 'middle': 0, 'major': 0}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2020-12-28 19:24:24 DEBUG (SyncWorker_4) [custom_components.neviweb130.climate] Updating neviweb130 climate OTH3600-GA-ZB (1.015 sec): {'roomSetpoint': 15, 'outputPercentDisplay': 100, 'roomTemperature': {'value': 14.84}, 'roomSetpointMin': 5, 'roomSetpointMax': 36, 'gfciStatus': 'ok', 'airFloorMode': 'floor', 'auxHeatConfig': 'off', 'loadWattOutput2': {'status': 'off', 'value': None}, 'loadConnected': 2136, 'lockKeypad': 'unlocked'}


Is this what you need?   
And its the Sinope 130 And the Ouellet 3600GA-ZB

**Comment by claudegel** [comment]
Thanks for the model number. I'll update my components for the Ouellet thermostats.
As for your other hijack Is it in HA ?

**Comment by canon102** [comment]
Yes, its on the dashboard in HA. I can add the cameras as a picture entity card. and they will work on the ipad. 
but not when i try and view my dashboard on the browser on my pc.

**Comment by claudegel** [comment]
Sorry but I don't have camera. Does your computer is a windows or a linux OS

**Comment by canon102** [comment]
I apologize for the secondary question, I will research that on my own. 

But back to the GT130 and the Ouellet 3600GA-ZB.

What other information can i get from the stat?

**Comment by canon102** [comment]
Can i measure the consumption on a graph?

**Comment by claudegel** [comment]
The 3600GA-ZB is fully supported in Neviweb130 as floor thermostat. check in dev tool/state. You will find your thermostat and the following properties:
hvac_modes: off, auto, heat
min_temp: 10
max_temp: 26
preset_modes: none, away, temporary
current_temperature: 22
temperature: 18
hvac_action: heating
preset_mode: none
wattage: 1824
gfci_status: ok
sensor_mode: floor
slave_heat: off
slave_status: off
slave_load: null
heat_level: 7
keypad: unlocked
rssi: null
id: 101013
friendly_name: Cuisine

in HA you can set sensor that record your floor temperature and transfer it to a graph.
```
- platform: template
  sensor:
    heat_level_plancher_solarium:
        friendly_name: "Intensité plancher solarium"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('climate.neviweb130_climate_plancher_solari', 'heat_level') }}"
```
this one record heating intensity. You can set other sensor to calculate the wattage measured by the thermostat x % heat_level t give you some idea of the concomtion in kw. Then use your electricity cost to do some calculation.

**Comment by claudegel** [comment]
Then in lovelace you can add some nice graph. You will need to dig a little but it is easy to do.

**Comment by canon102** [comment]
Thanks So much for the help! 
This is awesome

**Comment by claudegel** [comment]
I'm closing that issue now. Feel free to ask if you need more help
