### ISSUE TITLE
VA4200WZ neviweb130: Error on device update

### ISSUE THREAD

**Issue by JordanM1738** [claudegel/sinope-130#219]
Bonjour,
Depuis la version v2.6.2, ma valve wifi est indosponible (VA4200WZ).

<img width="202" alt="image" src="https://github.com/claudegel/sinope-130/assets/85708647/05cabb90-e9b7-4f38-809a-f54768e32032">

J'ai l'erreur suivante:

Merci.

Logger: homeassistant.components.valve
Source: helpers/entity_platform.py:599
Integration: Vanne (documentation, issues)
First occurred: 10:20:15 (1 occurrences)
Last logged: 10:20:15

neviweb130: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1261, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/valve.py", line 854, in update
    self._stm8Error_motorPosition = device_data[ATTR_STM8_ERROR]["motorPosition"]
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'motorPosition'

**Comment by claudegel** [comment]
Bonjour,
Pouvez-vous fournir la ligne des log de HA qui contient ceci pour votre valve.
`[custom_components.neviweb130.valve] Updating neviweb130 valve...`

**Comment by JordanM1738** [comment]
2024-02-11 10:20:15.421 DEBUG (SyncWorker_19) [custom_components.neviweb130.valve] Updating neviweb130 valve Sedna (0.346 sec): {'batteryVoltage': 5.4, 'batteryStatus': 'low', 'motorPosition': 100, 'motorTargetPosition': 100, 'temperatureAlarmStatus': 'ok', 'valveClosureSource': {'source': 'user'}, 'stm8Error': {'motorJam': False}, 'alertLowBatt': False, 'batteryStatusNormalized': 'low', 'batteryPercentNormalized': 0, 'backupPowerSupply': None}
2024-02-11 10:20:15.427 ERROR (MainThread) [homeassistant.components.valve] neviweb130: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1261, in async_device_update
await hass.async_add_executor_job(self.update)
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/neviweb130/valve.py", line 854, in update
self._stm8Error_motorPosition = device_data[ATTR_STM8_ERROR]["motorPosition"]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'motorPosition'

**Comment by claudegel** [comment]
Ok vous n'avez que l'attribut 'stm8Error': {'motorJam': False}, le motorPosition n'est pas supporté pour cette valve. je vais faire une patch et je vous avise

**Comment by claudegel** [comment]
Voici, seulement copier le fichier valve.py du lien ci-dessous pour remplacer le votre dans HA et redémarre HA
https://github.com/claudegel/sinope-130/tree/valve-delay/custom_components/neviweb130

**Comment by JordanM1738** [comment]
2024-02-11 18:20:59.769 ERROR (MainThread) [homeassistant.components.valve] neviweb130: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1261, in async_device_update
await hass.async_add_executor_job(self.update)
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/neviweb130/valve.py", line 855, in update
if ATTR_STM8_ERROR["motorPosition"] in device_data:
~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by claudegel** [comment]
OK I've made some changes in valve.py

**Comment by JordanM1738** [comment]
Tout est beau ça corrige le problème. 
Merci beaucoup !

**Comment by claudegel** [comment]
Parfait un de réglé il m'en reste deux autres :)

**Comment by claudegel** [comment]
je vais faire un release ce soir
