### ISSUE TITLE
Add a new model number for Leak Sensor

### ISSUE THREAD

**Issue by jfauger** [claudegel/sinope-130#231]
I bought a new sedna valve and the leak sensor weren't showing as entities. When looking in the log I found that the model has been changed to 42102.  I changed line 122 in the sensor.py and the sensor could be seen as an entity.  Sensor.py should be revised to add this model.

Bonjour Claude, j'ai acheté une valve sedna et le sensor qui venait dans le kit n'apparaissait pas comme entité.  En regardant dans le code j'ai vu que le nom a été modifié pour 42102. J'ai modifié la ligne 122 du sensor.py pour y ajouter le model 42102 et mon sensor est apparu comme entité.

LOG :
2024-03-13 17:00:03.691 DEBUG (SyncWorker_0) [custom_components.neviweb130] Received gateway data: [{'id': 522272, 'identifier': '500b91400005c1e2-2c1165fffeae85a3', 'name': 'Kitchen Sink', 'family': '4210-VA', 'signature': {'model': 42102, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 0, 'middle': 2, 'minor': 0}, 'hardRev': 0}, 'location$id': 98387, 'parentDevice$id': 522271, 'group$id': 256093, 'orderIdx': 0, 'sku': 'WL4210', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None},

**Comment by claudegel** [comment]
C'est bon ça. Est-ce que ton sensor est connecté directement à la valve ou bien au GT130

**Comment by jfauger** [comment]
Connecté à la valve. Je n'ai pas pas le gateway.

**Comment by claudegel** [comment]
Peux-tu regarder les attribut transmit par Neviweb quand tu es connecté à Neviweb.com pour ce sensor.
Il faut aller dans la config du sensor et avec firefox cliquer sur F12 pour activer la console de debug.Tu devrais voir passer les attribut.
![firefox console](https://github.com/claudegel/sinope-130/assets/4268938/8a817511-19ab-4a65-a67a-907d34118070)

**Comment by claudegel** [comment]
Je pense qu'il va falloir créer un entité à part car sinon tu auras pas la configuration cfgValveClosure

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 214931](https://github.com/claudegel/sinope-130/assets/56693244/3b46ee0c-a6b6-4c5b-89e8-2aeee41a3229)

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 215029](https://github.com/claudegel/sinope-130/assets/56693244/4f16938c-7c7b-4366-ba8b-4e8201ce5a73)

**Comment by claudegel** [comment]
As-tu une configuration pour fermer la valve en cas de fuite dans neviweb pour ton sensor ?

**Comment by jfauger** [comment]
oui. 
![Screenshot 2024-03-13 215604](https://github.com/claudegel/sinope-130/assets/56693244/7db19393-414a-4f3b-840b-6024575edd87)

**Comment by claudegel** [comment]
change le premier et regardes la console il va y avoir un parametre cfgValveClosure ou bien alertWaterLeak

**Comment by claudegel** [comment]
Il y a aussi le dernier qui doit être alertLowTemp

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 220434](https://github.com/claudegel/sinope-130/assets/56693244/d2c0d68b-468b-4970-953a-d08ee7b8fece)

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 220532](https://github.com/claudegel/sinope-130/assets/56693244/25ddb438-5ca2-49a1-a531-90788a498b38)

**Comment by claudegel** [comment]
Ok ca confirme. C,est quoi les differente valeur pour Action in case...

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 220806](https://github.com/claudegel/sinope-130/assets/56693244/18141188-ac9c-48af-beac-6cb168b61a59)

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 220806](https://github.com/claudegel/sinope-130/assets/56693244/0d56a332-89b2-476e-8b5d-49c5000f933e)

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 220906](https://github.com/claudegel/sinope-130/assets/56693244/cb498aa8-dd4c-4e35-a82d-405e6bc69473)
ca cest avec closed the valve only

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 221221](https://github.com/claudegel/sinope-130/assets/56693244/f19e89f6-97c2-4aef-9b7d-a9b1fc541e63)

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 221427](https://github.com/claudegel/sinope-130/assets/56693244/1b9e1451-763a-4461-8c4f-899f7cabc78e)

je pense que j'ai couvert tous les cas...

**Comment by claudegel** [comment]
si tu click sur Request au lieu de Response. On va voir la commande qui est envoyée au serveur

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 222324](https://github.com/claudegel/sinope-130/assets/56693244/53fb0c58-eba7-4081-9c13-5a98e405e6ea)

**Comment by claudegel** [comment]
OK cfgValveClosure est à ON quand il est sur une des 3 premier choix et à OFF pour No action.
si tu choisis le premier c,est quoi le request

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 222615](https://github.com/claudegel/sinope-130/assets/56693244/9c506b1b-2eb7-46bd-b20b-9c2f6a12f424)
![Screenshot 2024-03-13 222640](https://github.com/claudegel/sinope-130/assets/56693244/0f91378b-e454-4bab-8d52-75e11f25d9fe)

**Comment by jfauger** [comment]
alertWaterLeak:  envoi alerte sur fermeture de valve (1)  et n'envoi rien avec (0)
alertLowBatt:  envoi alerte low batterie (1) et n'envoie rien avec (0)
alertLowTemp : envoi alerte low temp (1) et n'envoie rien avec (0).
cfgValveClosure:''on'' ou ''off'' ferme ou pas la valve sur une alerte

**Comment by claudegel** [comment]
Ah je vois qu'on regarde pas a la bonne place. Il faut regarder la ligne attribute pour voir passer la commande
https://neviweb.com/api/device/183416/attribute

**Comment by jfauger** [comment]
le lien ne marche pas de mon coté...  je ne suis pas un expert en informatique...mais je pense que je regardais a la bonne place je regardais les PUT request et non les GET request.  Je ne vois pas de json attribute quand je fais les changements.

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 222640](https://github.com/claudegel/sinope-130/assets/56693244/ff39450f-33f2-4a14-84b9-959afeebe9b7)
finalement j'en ai vu 1...

**Comment by jfauger** [comment]
mauvaise photo...celle-ci est bonne 
![Screenshot 2024-03-13 223915](https://github.com/claudegel/sinope-130/assets/56693244/5424ecfe-c55c-4e4f-97f0-5a24f62bec4b)

**Comment by claudegel** [comment]
Non c,est beau on a:
close vale and send alert: cfgValveClosure:''on'' , alertWaterLeak: 1
close valve only: cfgValveClosure:''on'' , alertWaterLeak: 0
send an alert only: cfgValveClosure:''off'' , alertWaterLeak: 1
No action: cfgValveClosure:''off'' , alertWaterLeak: 0

avec ça je vais développer une nouvelle section pour ce sensor et ajouter le service pour ajuster ces parametres.
Je vasi te faire signe quand je vais avoir la nouvelle version a tester

**Comment by jfauger** [comment]
![Screenshot 2024-03-13 224042](https://github.com/claudegel/sinope-130/assets/56693244/c50fcbfa-f909-4368-8b3a-779bdab7c943)

**Comment by jfauger** [comment]
J'arrive a la meme conclusion que toi.  Fais-moi signe quand tu seras pret.  Merci pour ton temps.

**Comment by claudegel** [comment]
Derniere chose pour action in case of risk of frost c,est quoi les valeur pour le PUT.... attribute
Même chose pour le action low batteries

**Comment by claudegel** [comment]
OK j'ai complètement séparé les détecteur connectés au GT130 de ceux connectés à la valve Sedna. Ça devrait simplifier les choses si Sinopé ajoute des models. J'ai mis les changements dans la branche:
https://github.com/claudegel/sinope-130/tree/Error-message. 
Il y a aussi dans cette branche une mise a jour les messages d'erreur de Neviweb et quelques bug fix.
Tu peux tester si tu veux

**Comment by jfauger** [comment]
J'imagine qu'il faut que je telecharge le zip et que manuellement je copie au bon endroit comme indiqué dans les README ?

**Comment by claudegel** [comment]
Oui et tu le place dans config/custom_components/neviweb130. Tu remplaces les fichiers qui sont là.
Par contre je pense que tu peux aussi copier seulement sensor.py et le mettre dans ton sensor.py

**Comment by jfauger** [comment]
J'ai effacé mes anciens leak sensors et j'ai redémarré HA. Dans ma liste d'entities de HA, je ne vois que ma valve sedna.  Aucun nouveaux sensors pour les leak detectors.  Je vois pourtant défilé l'information de mes sensors dans le log

Voici une copie du log :

024-03-18 20:11:48.049 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received gateway data: [{'id': 522400, 'identifier': '500b91400005c1e2-500b914000055935', 'name': 'Ground Floor Bathroom', 'family': '5052', 'signature': {'model': 5052, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 1, 'middle': 1, 'minor': 3}, 'hardRev': 0}, 'location$id': 98387, 'parentDevice$id': 522271, 'group$id': 256148, 'orderIdx': 0, 'sku': 'WL4200S', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 522272, 'identifier': '500b91400005c1e2-2c1165fffeae85a3', 'name': 'Kitchen Sink', 'family': '4210-VA', 'signature': {'model': 42102, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 0, 'middle': 2, 'minor': 0}, 'hardRev': 0}, 'location$id': 98387, 'parentDevice$id': 522271, 'group$id': 256093, 'orderIdx': 0, 'sku': 'WL4210', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 522271, 'identifier': '500b91400005c1e2', 'name': 'VA4220WF', 'family': '3150-1', 'signature': {'model': 3150, 'modelCfg': 2, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 6, 'minor': 2}, 'hardRev': 0}, 'location$id': 98387, 'parentDevice$id': None, 'group$id': 256094, 'orderIdx': 0, 'sku': 'VA4220WF', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 522379, 'identifier': '500b91400005c1e2-bc026efffe3fa45d', 'name': 'Washing Machine', 'family': '4210-VA', 'signature': {'model': 42102, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 0, 'middle': 2, 'minor': 0}, 'hardRev': 0}, 'location$id': 98387, 'parentDevice$id': 522271, 'group$id': 256138, 'orderIdx': 0, 'sku': 'WL4210', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}]
2024-03-18 20:11:48.050 DEBUG (SyncWorker_2) [custom_components.neviweb130] Gateway_data : [{'id': 522400, 'identifier': '500b91400005c1e2-500b914000055935', 'name': 'Ground Floor Bathroom', 'family': '5052', 'signature': {'model': 5052, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 1, 'middle': 1, 'minor': 3}, 'hardRev': 0}, 'location$id': 98387, 'parentDevice$id': 522271, 'group$id': 256148, 'orderIdx': 0, 'sku': 'WL4200S', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 522272, 'identifier': '500b91400005c1e2-2c1165fffeae85a3', 'name': 'Kitchen Sink', 'family': '4210-VA', 'signature': {'model': 42102, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 0, 'middle': 2, 'minor': 0}, 'hardRev': 0}, 'location$id': 98387, 'parentDevice$id': 522271, 'group$id': 256093, 'orderIdx': 0, 'sku': 'WL4210', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 522271, 'identifier': '500b91400005c1e2', 'name': 'VA4220WF', 'family': '3150-1', 'signature': {'model': 3150, 'modelCfg': 2, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 6, 'minor': 2}, 'hardRev': 0}, 'location$id': 98387, 'parentDevice$id': None, 'group$id': 256094, 'orderIdx': 0, 'sku': 'VA4220WF', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 522379, 'identifier': '500b91400005c1e2-bc026efffe3fa45d', 'name': 'Washing Machine', 'family': '4210-VA', 'signature': {'model': 42102, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 0, 'middle': 2, 'minor': 0}, 'hardRev': 0}, 'location$id': 98387, 'parentDevice$id': 522271, 'group$id': 256138, 'orderIdx': 0, 'sku': 'WL4210', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}]
2024-03-18 20:11:48.309 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 5052, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 1, 'middle': 1, 'minor': 3}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2024-03-18 20:11:48.649 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 42102, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 0, 'middle': 2, 'minor': 0}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2024-03-18 20:11:48.962 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 3150, 'modelCfg': 2, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 6, 'minor': 2}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2024-03-18 20:11:49.233 DEBUG (SyncWorker_2) [custom_components.neviweb130] Received signature data: {'signature': {'model': 42102, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 0, 'middle': 2, 'minor': 0}, 'hardRev': 0, 'protocol': 'sinopcom'}}

**Comment by jfauger** [comment]
et la suite qui pourrait etre intéressant ;

2024-03-18 20:11:49.239 DEBUG (SyncWorker_2) [custom_components.neviweb130] Setting scan interval to: 0:06:00
2024-03-18 20:11:49.241 DEBUG (SyncWorker_2) [custom_components.neviweb130] Setting Homekit mode to: False
2024-03-18 20:11:49.242 DEBUG (SyncWorker_2) [custom_components.neviweb130] Setting stat interval to: 1800
2024-03-18 20:11:50.498 DEBUG (MainThread) [custom_components.neviweb130.valve] Setting up neviweb130 valve VA4220WF: {'id': 522271, 'identifier': '500b91400005c1e2', 'name': 'VA4220WF', 'family': '3150-1', 'signature': {'model': 3150, 'modelCfg': 2, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 6, 'minor': 2}, 'hardRev': 0, 'protocol': 'sinopcom'}, 'location$id': 98387, 'parentDevice$id': None, 'group$id': 256094, 'orderIdx': 0, 'sku': 'VA4220WF', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}
2024-03-18 20:11:50.500 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up neviweb130 platform for sensor
Traceback (most recent call last):

**Comment by claudegel** [comment]
Il me faut la suite du log ci-dessus

**Comment by jfauger** [comment]
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/neviweb130/sensor.py", line 160, in async_setup_platform
    entities.append(Neviweb130ConnectedSensor(data, device_info, device_name, device_type, device_sku, device_firmware))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/sensor.py", line 705, in __init__
    self._is_monitor = false
                       ^^^^^
NameError: name 'false' is not defined. Did you mean: 'False'?

**Comment by claudegel** [comment]
Ok c'est corrigé. Tu peux télécharger sensor.py

**Comment by jfauger** [comment]
Le probleme est regle. A 1ere vue tout semble ok. Ce weekend je ferai d'autres verifications. Merci!

**Comment by claudegel** [comment]
Parfait je vais attendre pour faire un release

**Comment by jfauger** [comment]
salut Claude, basé sur les tests que j'ai fait je dirais que tout est ok.  J'ai testé le service : Sinope Neviweb130: set_sensor_alert et les changements sont bien ''poussés'' dans l'application neviweb.

**Comment by claudegel** [comment]
Ok je termine un autre bug pour une valve mesh et je vais publier en fin de semaine
