### ISSUE TITLE
Périphériques TH1124ZB introuvables (màj 2.8.9)

### ISSUE THREAD

**Issue by Gwen59800Qc** [claudegel/sinope-130#277]
Bonjour,

Tout d'abord, merci pour cette intégration merveilleuse !

Depuis la dernière màj faite aujourd'hui (la 2.8.9), j'ai tous mes périphériques TH1124ZB qui ne sont plus reconnus par l'intégration.

Mes autres périphériques (WL4200 et RM3250ZB n'ont pas de problème).

Je suis sous HA core 2024.11.04

J'ai des erreurs au redémarrage

 `Enregistreur: homeassistant.util.loop
Source: util/loop.py:77
S'est produit pour la première fois: 18:41:21 (1 occurrences)
Dernier enregistrement: 18:41:21

Detected blocking call to import_module with args ('custom_components.neviweb130.climate',) in /usr/src/homeassistant/homeassistant/loader.py, line 1300: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 166, in _async_component_platform_discovered await self.async_setup_platform(platform, {}, info) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 291, in async_setup_platform platform = await async_prepare_setup_platform( File "/usr/src/homeassistant/homeassistant/setup.py", line 538, in async_prepare_setup_platform platform = await integration.async_get_platform(domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 1104, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1169, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1094, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1268, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1300, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")`

`Enregistreur: homeassistant.loader
Source: loader.py:1268
S'est produit pour la première fois: 18:41:21 (2 occurrences)
Dernier enregistrement: 18:41:21

Unexpected exception importing platform custom_components.neviweb130.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1268, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1300, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/neviweb130/climate.py", line 281, in <module>
    | ClimateEntityFeature.SWING_HORIZONTAL_MODE
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ClimateEntityFeature' has no attribute 'SWING_HORIZONTAL_MODE'`

`Enregistreur: homeassistant.setup
Source: setup.py:497
S'est produit pour la première fois: 18:41:21 (1 occurrences)
Dernier enregistrement: 18:41:21

Unable to prepare setup for platform 'neviweb130.climate': Platform not found (Exception importing custom_components.neviweb130.climate).`

J'ai pourtant ma GT130 fonctionnelle et je me connecte à l'application neviweb sans problème où je peux voir tous mes périphériques.

Merci

**Comment by claudegel** [comment]
Simplement mettre a jour HA vers la version 2024.12.1
HA ont ajouté le support pour horizontal swing mode et les HP6000ZB-xx de Sinopé ont cette fonction. Ma dernière mise a jour était pour supporter cette fonction.

**Comment by Gwen59800Qc** [comment]
Je vais donc enfreindre une de mes règles de ne jamais mettre à jour la xxx.xx.1 afin de récupérer la fonction (ou patienter comme ça une semaine ou deux 😕)

Merci Claude ! 🙏🏻

**Comment by claudegel** [comment]
Non vous pouvez toujours reculé à la version précédente de neviweb130 en vous servant de HACS

**Comment by claudegel** [comment]
Dans HACS, choisissez l'option retélécharger pour neviweb130 et au bas de la fenêtre ouvrir «Besoin d'une version différente ?»

**Comment by Gwen59800Qc** [comment]
La dernière màj 2024.12.1 a causé beaucoup de trouble dans toutes mes
personnalisations... Je suis revenu à mon backup complet d'hier.

Je vais patienter pour toutes les mise à jour.

Merci encore

Le lun. 9 déc. 2024, 20 h 25, Claude Gelinas ***@***.***> a
écrit :

**Comment by claudegel** [comment]
Avez-vous essayé de reculer neviweb130 de une version et garder votre version de HA 2024.11.04
Désolé mais je dois suivre le développement de HA car ceux qui ont acheté des HP6000ZB-xx ou TH6500WF avaient des problèmes avec le swing horizontale.

**Comment by Gwen59800Qc** [comment]
Non, j'avais déjà upgradé vers 2024.12.1
Avec la version 2024.11.3 (mon ancienne version) je n'ai plus aucun problème.

Avec 2024.12.1 j'ai eu d'autres troubles sur mon HA (custom-card notamment) en plus de neviweb130

**Comment by claudegel** [comment]
Custom card a été mis a jour.

**Comment by Gwen59800Qc** [comment]
Merci Claude. On va tester cela dans les prochains jours

Le sam. 14 déc. 2024, 09 h 59, Claude Gelinas ***@***.***> a
écrit :

**Comment by claudegel** [comment]
Laissez-moi savoir s'il y a un problème mais je viens de pousser une nouvelle version qui contient les dernieres corrections.
