### ISSUE TITLE
TH1134ZB-HC

### ISSUE THREAD

**Issue by Deewian** [claudegel/sinope-130#279]
Bonjour,

Es ce qu'il y a eu un changement pour l'intégration du TH1134ZB-HC depuis la version 2.8.5? 

Je viens de tester un retour en arrière vers la version 2.8.5 et l'intégration fonctionne mais à partir de la version 2.8.7 je reçois un message que l'entitié n'est plus disponible depuis l'intégration neviweb130.

HA Core version 2024.12.5
HA Supervisor 2024.12.0

**Comment by claudegel** [comment]
On va verifier ça mais à ma conaissance je n'ai pas changé sauf peut-être l'ajout du swing_horizontal_mode que HA a ajouté aux thermostats début décembre.
Avez-vous des log il me faudrait la ligne contenant ceci
[custom_components.neviweb130.climate] Updating neviweb130 climate «nom de votre thermostat»...
Probablement un attribut qui n'est pas accepté par Neviweb

**Comment by claudegel** [comment]
Je vois que dans Neviweb il y a deux type de thermostats TH1134ZB-HC
- un qui fonctionne comme un thermostat ordinaire
- un qui supporte les pompes a chaleur
Quel est le Modèle de votre thermostat dans Neviweb section info

**Comment by claudegel** [comment]
A la version 2.8.7 j'ai ajouté le swing mode pour les TH1134ZB-HC. C'est probablement cela le problème. Il faut donc trouver une manière de différencier les deux modèles de TH1134ZB-HC

**Comment by Deewian** [comment]
Voici ce que j’ai dans la section info

TH1134ZB-HC
Model: 1512
Software Version: 0.2.2
Hardware Version: 3

**Comment by claudegel** [comment]
dans vos log est-ce qu'il y a un message d'erreur avec DVCATTRNSPTD
Aussi il faut trouver ce qui différencie les deux TH1134ZB-HC dont un a le support pour les thermopompe et l'autre non. Je suspecte que le votre ne supporte pas les thermopompe. Est-ce que dans neviweb il y a une option pour activer le support des thermopompes. soit en choisissant un model de thermopompe ou autre chose

**Comment by claudegel** [comment]
Il y a le parametre **hcDevice** dans la liste des parametres du TH1134ZB-HC. Est-ce qu'il y a une selection possible dans Neviweb pour activer un model de thermopompe ou laisser a **Aucun** ou quelque chose du genre.
Pouvez-vous me faire un printscreen des differents parametres pour **configuration de l'appareil** et **avancee**

**Comment by Deewian** [comment]
Voici une copie rapide de logs dans HA

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:927
integration: Climate (documentation, issues)
First occurred: 09:00:31 (1 occurrences)
Last logged: 09:00:31

Error adding entity climate.neviweb130_climate_thermostat for domain climate with platform neviweb130
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1384, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1089, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 337, in __getattribute__
    return super().__getattribute__(name)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/neviweb130/climate.py", line 3502, in extra_state_attributes
    'fan_capability': extract_capability(self._fan_cap),
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/climate.py", line 1041, in extract_capability
    value = {i for i in cap if cap[i]==True}
                               ~~~^^^
TypeError: string indices must be integers, not 'str'

Je ne crois pas avoir qqchose en option dans neviweb pour la thermopompe. 

![IMG_0851](https://github.com/user-attachments/assets/e58624f0-a474-4db6-ba11-19c40759d857)

**Comment by claudegel** [comment]
Dans configuration vous avez quoi

**Comment by claudegel** [comment]
Dans les log est-ce qu'il y a une ligne qui contient ceci:
[custom_components.neviweb130.climate] Updating neviweb130 climate...
Il semble que la valeur de self._fan_cap ou ATTR_FAN_CAP, fanCapabilities soit la cause de l'erreur

**Comment by Deewian** [comment]
Voici les options de configuration. J’ai vérifié dans les sous menu et je n’ai rien en lien avec une thermopompe. 

Pour les logs non je ne retrouve rien qui soit [custom_components.neviweb130.climate] Updating neviweb130 climate... 

Seulement les mêmes que les logs d’avant. 

![IMG_0852](https://github.com/user-attachments/assets/9397bee2-2ddd-4ad1-997c-cfcc86cd30b2)
![IMG_0853](https://github.com/user-attachments/assets/2e7d0da0-3d9c-4610-8866-49b7c82df5ee)

**Comment by claudegel** [comment]
J'ai cree la branche TH1134ZB-HC avec une correction dans climate.py
https://github.com/claudegel/sinope-130/tree/TH1124ZB-HC/custom_components/neviweb130
copiez le fichier climate.py et ecrasez celui dans config/custom_components/neviweb130
assurez-vous d'avoir la version 2.9.0
Pour les log il faut les activer dans configuration.yaml comme ceci
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```

**Comment by claudegel** [comment]
Pouvez-vous me montrer les valeurs possibles pour le parametre secondary display. Il semble que vous ayez une option que les autres thermostats n'ont pas: Time and outdor temperature

**Comment by Deewian** [comment]
Oui voici les options

![IMG_0854](https://github.com/user-attachments/assets/9c191350-ec0b-4087-8a9d-355cd75ddf56)

**Comment by claudegel** [comment]
OK alors j'ai bien hâte de voir comment Sinopé les appel quand on recoit les attributs. présentement vous être en mode time and outdoor temperature. Ça va me prendre les valeurs pour que je puisse modifier le service set_second_display. On pourra les voir quand vous aurez les log de la ligne
`[custom_components.neviweb130.climate] Updating neviweb130 climate...`

On trouve ça dans le fichier home-assistant.log

**Comment by Deewian** [comment]
Voici la ligne complète du log en question:

2024-12-28 17:38:51.602 DEBUG (SyncWorker_0) [custom_components.neviweb130.climate] Updating neviweb130 climate Salon - Chauffage (2.485 sec): {'drStatus': {'drActive': 'off', 'optOut': 'off', 'setpoint': 'off', 'powerAbsolute': 'off', 'powerRelative': 'off'}, 'outputPercentDisplay': 0, 'roomSetpoint': 23, 'coolSetpoint': 26, 'systemMode': 'heat', 'hcDevice': None, 'fanSpeed': 'auto', 'fanSwingVertical': 'off', 'fanSwingHorizontal': 'off', 'roomTemperatureDisplay': 24.5, 'drSetpoint': {'status': 'off', 'value': None}, 'roomSetpointMax': 30, 'roomSetpointMin': 5, 'temperatureFormat': 'celsius', 'timeFormat': '24h', 'config2ndDisplay': 'exteriorTemperature', 'rssi': -54, 'coolSetpointMin': 16, 'coolSetpointMax': 30, 'cycleLength': 15, 'loadConnected': 2019, 'backlightAdaptive': 'always', 'lockKeypad': 'unlocked', 'language': 'en', 'fanCapabilities': 'low/med/high/auto', 'fanSwingCapabilities': {'fullHorizontal': False, 'autoHorizontal': False, 'fullVertical': False, 'autoVertical': False}, 'fanSwingCapabilityHorizontal': {'fixedRegion1': False, 'fixedRegion2': False, 'fixedRegion3': False, 'fixedRegion4': False, 'fixedRegion5': False, 'fixedRegion6': False, 'fixedRegion7': False, 'fixedRegion8': False, 'swingRegion1': False, 'swingRegion2': False, 'swingRegion3': False, 'swingRegion4': False, 'swingRegion5': False, 'swingRegion6': False, 'swingRegion7': False, 'swingRegion8': False}, 'fanSwingCapabilityVertical': {'fixedRegion1': False, 'fixedRegion2': False, 'fixedRegion3': False, 'fixedRegion4': False, 'fixedRegion5': False, 'fixedRegion6': False, 'fixedRegion7': False, 'fixedRegion8': False, 'swingRegion1': False, 'swingRegion2': False, 'swingRegion3': False, 'swingRegion4': False, 'swingRegion5': False, 'swingRegion6': False, 'swingRegion7': False, 'swingRegion8': False}, 'balancePoint': -10, 'heatLockoutTemperature': None, 'coolLockoutTemperature': None, 'availableMode': 'heatingOnly', 'displayConfig': 'disabled', 'displayCapability': {'disable': False, 'enable': False}, 'soundConfig': 'disabled', 'soundCapability': {'disable': False, 'enable': False}, 'model': None}

**Comment by Deewian** [comment]
J'ai de nouveau accès à l'information suite au remplacement du fichier climate.py

![image](https://github.com/user-attachments/assets/0c4ae446-874c-4ee8-b05c-4b754381e75a)

**Comment by claudegel** [comment]
Parfait. C'était bien le Fan_cap le problème.
Pourriez-vous changer dans Neviweb le secondary display à Time and setpoint et regarder dans home-assistant.log pour la prochaine mise a jour du thermostat pour voir la même ligne [custom_components.neviweb130.climate] Updating neviweb130 climate...
Pas besoin de redémarrer HA juste regarder vers la fin du fichier log pour avoir la derniere mise a jour du thermostat et me retourner cette ligne. je recherche ce parametre 'config2ndDisplay': 'exteriorTemperature', qui est l'option sélectionnée présentement

Même chose en changeant pour Ambiant temperature only. Comme ça je vais avoir l'info qu'il me faut.

Pour le reste conservez cette version jusqu'à la prochaine mise a jour de neviweb130.
Merci de votre aide.

**Comment by Deewian** [comment]
Oui voici l'info du log avec Time and Setpoint:
 'config2ndDisplay': 'setpoint', 'rssi': -55,

et avec Ambient Temperature Only:
 'config2ndDisplay': 'none', 'rssi': -56,

Laissez-moi savoir s'il faut autre chose. 

Merci a vous pour le support rapide et votre travail qui permet d'avoir cette intégration dans HA.

**Comment by claudegel** [comment]
Dernière chose quel sont les option pour language ? fr et en ?

**Comment by Deewian** [comment]
Oui dans Neviweb il y a seulement French et English comme option

**Comment by claudegel** [comment]
ok merci, je vais avouter les services set_language et set_hc_second_display
Ca va apparaitre dans la prochaine version.
