### ISSUE TITLE
Error adding VA4220WF valve

### ISSUE THREAD

**Issue by horspiste** [claudegel/sinope-130#36]
When HomeAssistant loads, I get this error:
Logger: homeassistant.components.switch
Source: custom_components/neviweb130/switch.py:276
Integration: Interrupteur (documentation, issues)
First occurred: 17:36:55 (1 occurrences)
Last logged: 17:36:55

neviweb130: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb130/switch.py", line 276, in update
    self._valve_closure = device_data[ATTR_VALVE_CLOSURE]["source"]
KeyError: 'valveClosureSource'

-=-
The error can be fixed by commenting out line 276 in switch.py.

Here are related I see in the debug log before the error:
2021-11-15 17:36:55 DEBUG (MainThread) [custom_components.neviweb130.switch] Setting up neviweb130 switch VA4220WF: {'id': 195927, 'identifier': '500b9140000180b9', 'name': 'VA4220WF', 'family': '3150-1', 'location$id': 27542, 'parentDevice$id': None, 'group$id': 64873, 'orderIdx': 0, 'sku': 'VA4220WF', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None, 'signature': {'model': 3150, 'modelCfg': 2, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 5, 'minor': 1}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2021-11-15 17:36:55 DEBUG (SyncWorker_6) [custom_components.neviweb130.switch] Updating neviweb130 switch VA4220WF (0.544 sec): {'motorPosition': 100, 'temperatureAlarmStatus': 'ok', 'batteryVoltage': 6.9, 'batteryStatus': 'ok', 'alertLowBatt': True}

**Comment by claudegel** [comment]
Hi good catch. I don't have this model so I wasn't able to test this valve model. I'll open a new branch «wifi-valve» to fix that.
It is possible that the ATTR_VALVE_CLOSURE is sent only when the valve close to know if it is closed manually or because of a leak detection. I need to test on my zigbee valve to see if it is the same

**Comment by claudegel** [comment]
I've made some changes in switch.py in the wifi-valve branch. Please test

**Comment by horspiste** [comment]
I've loaded the new switch.py file and all seems fine. Thank you!

Sylvain

**Comment by claudegel** [comment]
I've created a new release. Thank you for reporting this bug
