### ISSUE TITLE
Ajouter le support pour TH1400WF

### ISSUE THREAD

**Issue by davcho80** [claudegel/sinope-130#38]
Comme demande dans le forum ajouter le support pour le Sinope TH1400WF
Merci

**Comment by claudegel** [comment]
Bonjour, dans la branche low-wifi j'ai modifié climate.py. récupère-le et installe le dans ton HA dans custom_component/neviweb130 à la place du climate.py 

Redémarre HA puis regardes les log pour la ligne [custom_components.neviweb130.sensor] Updating neviweb130... qui concerne ce thermostat et envois moi cette ligne

Par la suite connecte toi a ton Neviweb et active la console de debug. Dans firefox c'est ctrl maj e. Dans google chrome c'est dans le coin haut droit les trois petits point à la verticale. Dans le menu tu sélectionnes plus d'outils puis Outils de développement. dis-moi quel navigateur tu as. on va voir passer tous les parametres reliés à ton thermostat et je pourrai valider et ajouter ce qui manque dans neviweb130

**Comment by davcho80** [comment]
2021-11-19 20:25:43 DEBUG (SyncWorker_4) [custom_components.neviweb130] Received signature data: {'signature': {'model': 739, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 3, 'minor': 7}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2021-11-19 20:25:43 DEBUG (SyncWorker_4) [custom_components.neviweb130] Setting scan interval to: 0:06:00
2021-11-19 20:25:43 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1400WF: {'id': 212152, 'identifier': '246f28fffea4e2dc', 'name': 'TH1400WF', 'family': '739', 'location$id': 37151, 'parentDevice$id': None, 'group$id': 71877, 'orderIdx': 0, 'sku': 'TH1400WF', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None, 'signature': {'model': 739, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 3, 'minor': 7}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2021-11-19 20:25:43 DEBUG (SyncWorker_2) [custom_components.neviweb130.climate] Updating neviweb130 climate TH1400WF (0.731 sec): {'roomSetpoint': 15, 'outputPercentDisplay': {'percent': 0, 'sourceType': 'heating'}, 'roomTemperature': {'value': 15.03, 'error': None}, 'roomSetpointMin': 5, 'roomSetpointMax': 36, 'timeFormat': '24h', 'temperatureFormat': 'celsius'}
2021-11-19 20:25:44 ERROR (MainThread) [homeassistant.components.climate] neviweb130: Error on device update!

**Comment by davcho80** [comment]
Tu veut une trace HAR?

**Comment by claudegel** [comment]
Désolé c'est quoi une trace HAR ?

**Comment by claudegel** [comment]
J'ai ramassé les attributs que tu as dans les log. Maintenant il faut vérifier si dans Neviweb il y en a d'autres a demander.
Valide dans Neviweb avec la console de débug

**Comment by davcho80** [comment]
Dans les outils de développement dans Network? je fait une trace et je t'evoi le fichier?

**Comment by claudegel** [comment]
oui

**Comment by davcho80** [comment]
[neviweb.com.zip](https://github.com/claudegel/sinope-130/files/7573729/neviweb.com.zip)

**Comment by davcho80** [comment]
en espérant que j'ai fait la bonne chose

**Comment by claudegel** [comment]
dans chrome, dans reseau tu selectionnes en dessous de filter «tout». Tu va voir a gauche une colonne ou defile des lignes comme attribute?attributes=...
selectionne la ligne de ton thermostat et a droite tu va voir tous les attributs. C'est ca que je veux

**Comment by davcho80** [comment]
{setpointMode: "manual", roomSetpoint: 15, roomTemperatureDisplay: {value: 15, status: "on"},…}
drSetpoint: {status: "off", value: null}
status: "off"
value: null
drStatus: {drActive: "off", optOut: "off", setpoint: "off", powerAbsolute: "off", powerRelative: "off"}
drActive: "off"
optOut: "off"
powerAbsolute: "off"
powerRelative: "off"
setpoint: "off"
occupancyMode: "none"
outputPercentDisplay: {percent: 0, sourceType: "heating"}
percent: 0
sourceType: "heating"
roomSetpoint: 15
roomTemperatureDisplay: {value: 15, status: "on"}
status: "on"
value: 15
setpointMode: "manual"

ca??

**Comment by claudegel** [comment]
Non ton neviweb.com.zip c'est pas bon. Je cherche ceci 
{"roomSetpoint":18,"roomTemperature":{"value":22.43},"outputPercentDisplay":0,"gfciStatus":"ok"}
Il faut trouver la ligne de ton thermostat et copier ce qui est listé à droite[](url
![debug](https://user-images.githubusercontent.com/4268938/142710742-acd48d32-19c1-4c41-b381-ac429fd23ca6.png)
)

**Comment by claudegel** [comment]
OK la c'est bon la liste que tu m'envois. Je vais pouvoir travailler sur climate.py
Ce sont bien les attributs de ton TH1400WF ?

**Comment by davcho80** [comment]
c'est le seul thermostat que j'ai dans Neviweb donc je pense que oui

**Comment by claudegel** [comment]
C'est un thermostat 24 volt ? as-tu un chauffage secondaire qui est aussi controlé par ce thermostat ?

**Comment by davcho80** [comment]
24 volt oui, non pas de chauffage secondaire

**Comment by claudegel** [comment]
il y a les attributs suivants que je ne connais pas
drSetpoint
drStatus

peux tu m'envoyer un print screen de ceci pour ton thermostat
![debug1](https://user-images.githubusercontent.com/4268938/142711931-9374d5e4-ca24-4079-a68a-a8bac6175bff.png)
![debug2](https://user-images.githubusercontent.com/4268938/142711934-90b585be-5b6e-4d2c-8c1f-8f728e8ae4e9.png)

t

**Comment by davcho80** [comment]
Voilà!


Le ven. 19 nov. 2021 à 21:47, Claude Gelinas ***@***.***> a
écrit :

**Comment by claudegel** [comment]
Je vois pas. Dans ton dernier message il y a rien

J'ai une version a tester. Il faut que tu load climate.py et const.py. J'ai modifié les duex fichiers

**Comment by davcho80** [comment]
![image_123986672](https://user-images.githubusercontent.com/94725371/142714041-e2dbc831-9d2b-485e-921f-1c9f8b960f0a.JPG)
![image_123986672 (1)](https://user-images.githubusercontent.com/94725371/142714066-334f2e79-f9a5-48c9-b785-8c9f6844030f.JPG)
![image_123986672 (2)](https://user-images.githubusercontent.com/94725371/142714069-a3796c03-c384-485e-944a-fba641bdb1df.JPG)


je test la version je te reviens

**Comment by claudegel** [comment]
Ha c'est bon il y a beaucoup plus d'attribut. Peux tu regarder dans la console de debug pour voir ces attribut et m'envoyer la liste comme tout a l'heur

**Comment by davcho80** [comment]
2021-11-19 23:17:39 ERROR (MainThread) [homeassistant.util.logging] Exception in discovery_platform_listener when dispatching 'discovery.platform_discovered_load_platform.climate': ({'service': 'load_platform.climate', 'platform': 'neviweb130', 'discovered': {}},)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 119, in discovery_platform_listener
await task
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 140, in component_platform_discovered
await self.async_setup_platform(platform, {}, info)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 229, in async_setup_platform
platform = await async_prepare_setup_platform(
File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in async_prepare_setup_platform
platform = integration.get_platform(domain)
File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 846, in exec_module
File "<frozen importlib._bootstrap_external>", line 983, in get_code
File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/config/custom_components/neviweb130/climate.py", line 93
MODE_AUTO,
^
SyntaxError: invalid syntax

**Comment by claudegel** [comment]
Oups petit erreur j'ai corrigé climate.py

**Comment by davcho80** [comment]
{airFloorMode: "floor", setpointMode: "manual", backlightAutoDim: "alwaysOn",…}
airFloorMode: "floor"
backlightAutoDim: "alwaysOn"
config2ndDisplay: "default"
earlyStartCfg: "off"
floorSensorType: "10k"
keyboardLock: "unlock"
loadWatt: 0
loadWattOutput1: 0
loadWattOutput2: 0
roomSetpointAway: 15
roomSetpointMax: 36
roomSetpointMin: 5
setpointMode: "manual"
signature: {model: 739, modelCfg: 0, softBuildCfg: 0, softVersion: {major: 2, middle: 3, minor: 7}, hardRev: 0,…}
hardRev: 0
model: 739
modelCfg: 0
protocol: "sinopcom"
softBuildCfg: 0
softVersion: {major: 2, middle: 3, minor: 7}
major: 2
middle: 3
minor: 7
temperatureFormat: "celsius"
timeFormat: "24h"
wifiRssi: -80
{floorLimitHigh: {value: null, status: "off"}, floorLimitLow: {value: null, status: "off"},…}
auxCycleLength: 0
cycleLength: 900
floorLimitHigh: {value: null, status: "off"}
status: "off"
value: null
floorLimitLow: {value: null, status: "off"}
status: "off"
value: null
floorMaxAirTemperature: {value: null, status: "off"}
status: "off"
value: null
pumpProtection: {status: "on", frequency: 1, duration: 60}
duration: 60
frequency: 1
status: "on"

**Comment by davcho80** [comment]
2021-11-19 23:24:26 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1400WF: {'id': 212152, 'identifier': '246f28fffea4e2dc', 'name': 'TH1400WF', 'family': '739', 'location$id': 37151, 'parentDevice$id': None, 'group$id': 71877, 'orderIdx': 0, 'sku': 'TH1400WF', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None, 'signature': {'model': 739, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 3, 'minor': 7}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2021-11-19 23:24:30 DEBUG (SyncWorker_2) [custom_components.neviweb130.climate] Updating neviweb130 climate TH1400WF (4.181 sec): {'roomSetpoint': 15, 'outputPercentDisplay': {'percent': 0, 'sourceType': 'heating'}, 'roomTemperature': {'value': 15.06, 'error': None}, 'roomSetpointMin': 5, 'roomSetpointMax': 36, 'timeFormat': '24h', 'temperatureFormat': 'celsius', 'loadWatt': 0, 'wifiRssi': -80, 'keyboardLock': 'unlock', 'config2ndDisplay': 'default', 'setpointMode': 'manual', 'occupancyMode': 'none', 'roomTemperatureDisplay': {'value': 15, 'status': 'on'}}
2021-11-19 23:24:31 ERROR (MainThread) [homeassistant.components.climate] neviweb130: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/neviweb130/climate.py", line 476, in update
self._setpoint = device_data[ATTR_SETPOINT]
KeyError: 'setpoint'

**Comment by claudegel** [comment]
Corrigé

**Comment by claudegel** [comment]
reload climate.py et const.py

**Comment by davcho80** [comment]
2021-11-19 23:36:25 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1400WF: {'id': 212152, 'identifier': '246f28fffea4e2dc', 'name': 'TH1400WF', 'family': '739', 'location$id': 37151, 'parentDevice$id': None, 'group$id': 71877, 'orderIdx': 0, 'sku': 'TH1400WF', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None, 'signature': {'model': 739, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 3, 'minor': 7}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2021-11-19 23:36:25 ERROR (MainThread) [homeassistant.components.climate] neviweb130: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/neviweb130/climate.py", line 434, in update
LOW_WIFI_ATTRIBUTE = [ATTR_ROOM_TEMP_DISPLAY, ATTR_SETPOINT]
NameError: name 'ATTR_SETPOINT' is not defined

**Comment by claudegel** [comment]
Oups une petite correction dans climate.py

**Comment by claudegel** [comment]
Bon j'espere que ca fonctionne. Je continue demain matin pour ajouter les autres attribut que tu m'as envoyé

**Comment by davcho80** [comment]
Good merci beaucoup, ca semble bon. Aucun erreur dans les logs

2021-11-19 23:42:49 DEBUG (SyncWorker_3) [custom_components.neviweb130] Successfully logged in
2021-11-19 23:42:50 DEBUG (SyncWorker_3) [custom_components.neviweb130] Number of networks found on Neviweb: 1
2021-11-19 23:42:50 DEBUG (SyncWorker_3) [custom_components.neviweb130] Selecting Maison as network
2021-11-19 23:42:50 DEBUG (SyncWorker_3) [custom_components.neviweb130] Received gateway data: [{'id': 212152, 'identifier': '246f28fffea4e2dc', 'name': 'TH1400WF', 'family': '739', 'location$id': 37151, 'parentDevice$id': None, 'group$id': 71877, 'orderIdx': 0, 'sku': 'TH1400WF', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}]
2021-11-19 23:42:50 DEBUG (SyncWorker_3) [custom_components.neviweb130] Received signature data: {'signature': {'model': 739, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 3, 'minor': 7}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2021-11-19 23:42:50 DEBUG (SyncWorker_3) [custom_components.neviweb130] Setting scan interval to: 0:06:00
2021-11-19 23:42:50 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1400WF: {'id': 212152, 'identifier': '246f28fffea4e2dc', 'name': 'TH1400WF', 'family': '739', 'location$id': 37151, 'parentDevice$id': None, 'group$id': 71877, 'orderIdx': 0, 'sku': 'TH1400WF', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None, 'signature': {'model': 739, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 3, 'minor': 7}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2021-11-19 23:42:51 DEBUG (SyncWorker_4) [custom_components.neviweb130.climate] Updating neviweb130 climate TH1400WF (0.806 sec): {'roomSetpoint': 15, 'outputPercentDisplay': {'percent': 0, 'sourceType': 'heating'}, 'roomTemperature': {'value': 15.55, 'error': None}, 'roomSetpointMin': 5, 'roomSetpointMax': 36, 'timeFormat': '24h', 'temperatureFormat': 'celsius', 'loadWatt': 0, 'wifiRssi': -81, 'keyboardLock': 'unlock', 'config2ndDisplay': 'default', 'setpointMode': 'manual', 'occupancyMode': 'none', 'roomTemperatureDisplay': {'value': 15.5, 'status': 'on'}}

**Comment by claudegel** [comment]
Bon j'ai fais un gros ménage et ajouté plein d'attribut. De mon coté ça fonctionne mais je n'ai pas tom thermostat. Testes ça. Il y a des changements dans climate.py et const.py

**Comment by claudegel** [comment]
Si tu peux vérifier dans la console de chrome quand tu active le mode early start (démarrage anticipé) quel sont les parametre qui sont passé je voudrais ajouter un service set early start

**Comment by davcho80** [comment]
2021-11-20 20:26:49 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform neviweb130
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
extra_state_attributes = self.device_state_attributes
File "/config/custom_components/neviweb130/climate.py", line 579, in device_state_attributes
'aux_cycle_length': self._aux_cycle_lenght,
AttributeError: 'Neviweb130Thermostat' object has no attribute '_aux_cycle_lenght'
2021-11-20 20:26:49 ERROR (MainThread) [homeassistant.components.climate] Error while setting up neviweb130 platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
extra_state_attributes = self.device_state_attributes
File "/config/custom_components/neviweb130/climate.py", line 579, in device_state_attributes
'aux_cycle_length': self._aux_cycle_lenght,
AttributeError: 'Neviweb130Thermostat' object has no attribute '_aux_cycle_lenght'

**Comment by davcho80** [comment]
earlyStartCfg: "off"
il y a activer ou désactiver comme choix

**Comment by claudegel** [comment]
J'ai corrigé climate.py

**Comment by davcho80** [comment]
sound good pas d'erreur

2021-11-20 21:35:36 DEBUG (SyncWorker_1) [custom_components.neviweb130] Successfully logged in
2021-11-20 21:35:37 DEBUG (SyncWorker_1) [custom_components.neviweb130] Number of networks found on Neviweb: 1
2021-11-20 21:35:37 DEBUG (SyncWorker_1) [custom_components.neviweb130] Selecting Maison as network
2021-11-20 21:35:37 DEBUG (SyncWorker_1) [custom_components.neviweb130] Received gateway data: [{'id': 212152, 'identifier': '246f28fffea4e2dc', 'name': 'TH1400WF', 'family': '739', 'location$id': 37151, 'parentDevice$id': None, 'group$id': 71877, 'orderIdx': 0, 'sku': 'TH1400WF', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}]
2021-11-20 21:35:37 DEBUG (SyncWorker_1) [custom_components.neviweb130] Received signature data: {'signature': {'model': 739, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 3, 'minor': 7}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2021-11-20 21:35:37 DEBUG (SyncWorker_1) [custom_components.neviweb130] Setting scan interval to: 0:06:00
2021-11-20 21:35:37 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1400WF: {'id': 212152, 'identifier': '246f28fffea4e2dc', 'name': 'TH1400WF', 'family': '739', 'location$id': 37151, 'parentDevice$id': None, 'group$id': 71877, 'orderIdx': 0, 'sku': 'TH1400WF', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None, 'signature': {'model': 739, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 3, 'minor': 7}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2021-11-20 21:35:38 DEBUG (SyncWorker_5) [custom_components.neviweb130.climate] Updating neviweb130 climate TH1400WF (1.378 sec): {'roomSetpoint': 15, 'outputPercentDisplay': {'percent': 0, 'sourceType': 'heating'}, 'roomTemperature': {'value': 15.57, 'error': None}, 'roomSetpointMin': 5, 'roomSetpointMax': 36, 'timeFormat': '24h', 'temperatureFormat': 'celsius', 'loadWatt': 0, 'wifiRssi': -41, 'keyboardLock': 'unlock', 'config2ndDisplay': 'default', 'setpointMode': 'manual', 'occupancyMode': 'none', 'pumpProtection': {'status': 'on', 'frequency': 1, 'duration': 60}, 'floorMaxAirTemperature': {'value': None, 'status': 'off'}, 'roomTemperatureDisplay': {'value': 15.5, 'status': 'on'}, 'airFloorMode': 'floor', 'backlightAutoDim': 'alwaysOn', 'earlyStartCfg': 'off', 'floorSensorType': '10k', 'roomSetpointAway': 15, 'auxCycleLength': 0, 'cycleLength': 900, 'floorLimitHigh': {'value': None, 'status': 'off'}, 'floorLimitLow': {'value': None, 'status': 'off'}}

**Comment by claudegel** [comment]
Parfait. J'ai ajouté un service_set_early_start pour les thermostats wifi pour démarrer le chauffage anticipé.

si tu veux tester il faut downloader __init__.py, climate.py et services.yaml

**Comment by claudegel** [comment]
Il n'y a pas d'erreur dans les log. Il reste juste a tester le service sur ton thermostat

**Comment by claudegel** [comment]
Bon je vais publier cette version s'il y a quelques chose rapporte le ici ou sur le blog

**Comment by claudegel** [comment]
La branche low-wifi a été migrée vers le master et j'ai publier la version 0.7.0. Merci de ton aide

**Comment by davcho80** [comment]
Good j'ai mis a jour le plugin en passant par HACS toute semble OK, merci a toi pour le support rapide. content d'avoir pu te donner un coup de main.
