### ISSUE TITLE
Impossible to turn on lights

### ISSUE THREAD

**Issue by mictechca** [claudegel/sinope-130#8]
It's impossible to turn on a dimmer light (not tested with switch, only dimmer). I have the following error :

> Détails du journal ( ERROR )
> Sun Mar 01 2020 10:07:06 GMT-0500 (heure normale de l’Est nord-américain)
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 576, in async_request_call
>     await coro
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 601, in async_turn_on
>     await self.hass.async_add_job(ft.partial(self.turn_on, **kwargs))
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/neviweb130/light.py", line 135, in turn_on
>     if not self._is_on:
> AttributeError: **'Neviweb130Light' object has no attribute '_is_on'**

**Comment by claudegel** [comment]
Could you tell me which HA version you are on. Also, as I don't have dimmer on my GT130 I cannot get the data sent by Neviweb. Could you open Neviweb in your browser and open the development console to see what parameter and data Neviweb is returning when you select a dimmer. To open the console just hit Ctrl/Shitf/E at the same time then go to Console in the menu.
Send me what you get.
for an outlet I get:
```
URL de la requête :https://neviweb.com/api/device/111044/attribute?attributes=onOff
response: onOff : off
```

**Comment by claudegel** [comment]
If you also have light switch could you also send back the attributes for those switch. That will allow me to update the code for both

**Comment by claudegel** [comment]
I've started a new branch "Light and dimmer", try it. You just need to copy the light.py file.
But I still need to get the real attributes for light and dimmer from Neviweb.
Let me know.

**Comment by mictechca** [comment]
Hi Claude,

I’m really sorry for the late late response but I thing you merged that branch into master and the _is_on function/variable is still invalid. So it makes it invalid when I want to turn on a light.
If you want to try a new branch I’ll be more available to help you with this.

Thanks!
Michael

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Claude Gelinas <notifications@github.com>
Envoyé : Sunday, March 1, 2020 2:38:24 PM
À : claudegel/sinope-130 <sinope-130@noreply.github.com>
Cc : mictechca <mic_hb@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [claudegel/sinope-130] Impossible to turn on lights (#8)


I've started a new branch "Light and dimmer", try it. You just need to copy the light.py file.
But I still need to get the real attributes for light and dimmer from Neviweb.
Let me know.

**Comment by claudegel** [comment]
Hi Michael,
no problem for the delay. I'm also very busy because I'm still working
in agri-food industries as food safety manager. Everything is a little
crasy.

I've plenty of light and dimmer connected to my gt125 but non for my
gt130 so I'm blind. I need to see what you get from neviweb in your
log, especially the line  like what I get for the thermostat:

signature data:

2020-04-14 22:28:27 DEBUG (MainThread) [custom_components.neviweb130] Received signature data: {'signature': {'model': 737, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 9, 'middle': 0, 'major': 1}, 'hardRev': 2, 'protocol': 'sinopcom'}}

device setting:

2020-04-14 22:28:36 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate Plancher cuisin: {'id': 101013, 'identifier': '500b914000021fb7', 'name': 'Plancher cuisin', 'family': '737', 'location$id': 16515, 'parentDevice$id': 98684, 'group$id': 16601, 'sku': 'TH1300ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None, 'signature': {'model': 737, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 9, 'middle': 0, 'major': 1}, 'hardRev': 2, 'protocol': 'sinopcom'}}

devices update:

2020-04-14 22:28:37 DEBUG (SyncWorker_3) [custom_components.neviweb130.climate] Updating neviweb130 climate Plancher cuisin (0.584 sec): {'roomSetpoint': 18, 'outputPercentDisplay': 0, 'roomTemperature': {'value': 23.71}, 'roomSetpointMin': 10, 'roomSetpointMax': 26, 'loadConnected': 1860, 'gfciStatus': 'ok', 'airFloorMode': 'floor'}


the last one is the most important. If you can please send those for
light and for dimmer.

You can also open neviweb in your bowser and hit «ctrl shitf e» at the
same time to open the debuf console. Select «Console» in the to menu.
You will see a lot of data. Select one of your light or dimmer and you
will get the attributes  for that device like what i have for my
thermostat below:

GEThttps://neviweb.com/api/device/106106/attribute?attributes=roomSetpoint,roomTemperature,outputPercentDisplay,gfciStatus

I need the attributes for each light and dimmer.

Thank's for helping to solve that issue.

Claude Gelinas

Le Wed, 15 Apr 2020 16:39:26 -0700
mictechca <notifications@github.com> a écrit:

**Comment by claudegel** [comment]
I just open a new branch to fix that issue. The old branch was merged because I was thinking that the changes fix your problem.

**Comment by mictechca** [comment]
Hi Claude,

Here are the requested infos :
2020-04-17 14:07:44 DEBUG (MainThread) [custom_components.neviweb130] Received gateway data: [{'id': 112496, 'identifier': '500b91400001e72b', 'name': 'Ch prin 1', 'family': '2131', 'location$id': 16666, 'parentDevice$id': 99405, 'group$id': 22261, 'sku': 'DM2500ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 112497, 'identifier': '500b91400001ea8c', 'name': 'Ch prin 2', 'family': '2131', 'location$id': 16666, 'parentDevice$id': 99405, 'group$id': 22261, 'sku': 'DM2500ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 102739, 'identifier': '500b914000021537', 'name': 'Foyer', 'family': '737-LV', 'location$id': 16666, 'parentDevice$id': 99405, 'group$id': 17493, 'sku': 'TH1400ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 99405, 'identifier': 'ccccccfffe6fb80a', 'name': 'GT130', 'family': 'GT130', 'location$id': 16666, 'parentDevice$id': None, 'group$id': None, 'sku': None, 'vendor': None, 'url_en': None, 'url_fr': None}, {'id': 112499, 'identifier': '500b91400001e390', 'name': 'Sdb haut évier', 'family': '2131', 'location$id': 16666, 'parentDevice$id': 99405, 'group$id': 22262, 'sku': 'DM2500ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}]
2020-04-17 14:07:45 DEBUG (MainThread) [custom_components.neviweb130] Received signature data: {'signature': {'model': 2131, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 2, 'middle': 3, 'major': 1}, 'hardRev': 2, 'protocol': 'sinopcom'}}
2020-04-17 14:07:45 DEBUG (MainThread) [custom_components.neviweb130] Received signature data: {'signature': {'model': 2131, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 2, 'middle': 3, 'major': 1}, 'hardRev': 2, 'protocol': 'sinopcom'}}
2020-04-17 14:07:45 DEBUG (MainThread) [custom_components.neviweb130] Received signature data: {'signature': {'model': 7372, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 7, 'middle': 0, 'major': 0}, 'hardRev': 2, 'protocol': 'sinopcom'}}
2020-04-17 14:07:45 DEBUG (MainThread) [custom_components.neviweb130] Received signature data: {'signature': {'model': 130, 'modelCfg': 1, 'softBuildCfg': 0, 'softVersion': {'major': 1, 'middle': 11, 'minor': 7}, 'hardRev': 3, 'protocol': 'sinopcom'}}
2020-04-17 14:07:45 DEBUG (MainThread) [custom_components.neviweb130] Received signature data: {'signature': {'model': 2131, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 2, 'middle': 3, 'major': 1}, 'hardRev': 2, 'protocol': 'sinopcom'}}

The model 7372 is my 24v thermostat and is working fine. I only have dimmers unfortunately for you which seems to be model 2131.
-----
2020-04-17 14:07:55 DEBUG (MainThread) [custom_components.neviweb130.light] Setting up neviweb130 light dimmer Ch prin 1: {'id': 112496, 'identifier': '500b91400001e72b', 'name': 'Ch prin 1', 'family': '2131', 'location$id': 16666, 'parentDevice$id': 99405, 'group$id': 22261, 'sku': 'DM2500ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None, 'signature': {'model': 2131, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 2, 'middle': 3, 'major': 1}, 'hardRev': 2, 'protocol': 'sinopcom'}}
-----
2020-04-17 14:07:56 DEBUG (SyncWorker_16) [custom_components.neviweb130.light] Updating neviweb130 light dimmer Ch prin 2 (0.271 sec): {'intensity': 0, 'onOff': 'off'}

In my browser console, here is the URL :
https://neviweb.com/api/device/112496/attribute?attributes=intensity,onOff

Thank you and have a nice day!


De : Claude Gelinas<mailto:notifications@github.com>
Envoyé le :15 avril 2020 20:55
À : claudegel/sinope-130<mailto:sinope-130@noreply.github.com>
Cc : mictechca<mailto:mic_hb@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [claudegel/sinope-130] Impossible to turn on lights (#8)

Hi Michael,
no problem for the delay. I'm also very busy because I'm still working
in agri-food industries as food safety manager. Everything is a little
crasy.

I've plenty of light and dimmer connected to my gt125 but non for my
gt130 so I'm blind. I need to see what you get from neviweb in your
log, especially the line like what I get for the thermostat:

signature data:

2020-04-14 22:28:27 DEBUG (MainThread) [custom_components.neviweb130] Received signature data: {'signature': {'model': 737, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 9, 'middle': 0, 'major': 1}, 'hardRev': 2, 'protocol': 'sinopcom'}}

device setting:

2020-04-14 22:28:36 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate Plancher cuisin: {'id': 101013, 'identifier': '500b914000021fb7', 'name': 'Plancher cuisin', 'family': '737', 'location$id': 16515, 'parentDevice$id': 98684, 'group$id': 16601, 'sku': 'TH1300ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None, 'signature': {'model': 737, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 9, 'middle': 0, 'major': 1}, 'hardRev': 2, 'protocol': 'sinopcom'}}

devices update:

2020-04-14 22:28:37 DEBUG (SyncWorker_3) [custom_components.neviweb130.climate] Updating neviweb130 climate Plancher cuisin (0.584 sec): {'roomSetpoint': 18, 'outputPercentDisplay': 0, 'roomTemperature': {'value': 23.71}, 'roomSetpointMin': 10, 'roomSetpointMax': 26, 'loadConnected': 1860, 'gfciStatus': 'ok', 'airFloorMode': 'floor'}


the last one is the most important. If you can please send those for
light and for dimmer.

You can also open neviweb in your bowser and hit «ctrl shitf e» at the
same time to open the debuf console. Select «Console» in the to menu.
You will see a lot of data. Select one of your light or dimmer and you
will get the attributes for that device like what i have for my
thermostat below:

GEThttps://neviweb.com/api/device/106106/attribute?attributes=roomSetpoint,roomTemperature,outputPercentDisplay,gfciStatus

I need the attributes for each light and dimmer.

Thank's for helping to solve that issue.

Claude Gelinas

Le Wed, 15 Apr 2020 16:39:26 -0700
mictechca <notifications@github.com> a écrit:

**Comment by claudegel** [comment]
Ok I've updated the code. Please try it. Branch attribute-is_on

**Comment by claudegel** [comment]
I also need some info. Could you open Neviweb and with the debug console open, select one of your dimmer and open it. Set the intensity to let say 50% then close the light.
Open the light again and see in the debug console for the parameters if you have this:
XHRPUThttps://neviweb.com/api/device/69458/attribute
JSON	
intensity	101
Transmission de la requête	
{"intensity":101}

I need to know if intensity is set to 101 to open the dimmer to the same intensity it was before you close it.
his is the way Neviweb GT125 is working and I suppose that GT130 use the same but I can't check it on my side.

**Comment by mictechca** [comment]
The light.py from the new branch doesn’t work to turn the lights on. No exception in the logs, but onOff stays off :
2020-04-22 18:53:28 DEBUG (SyncWorker_2) [custom_components.neviweb130.light] Updating neviweb130 light dimmer Ch prin 1 (0.169 sec): {'intensity': 0, 'onOff': 'off'}
2020-04-22 18:53:33 DEBUG (SyncWorker_17) [custom_components.neviweb130.light] Updating neviweb130 light dimmer Ch prin 1 (0.142 sec): {'intensity': 0, 'onOff': 'off'}

Concerning the request you wanted me to check, it only sets onOff parameter to on or off without any intensity param. {« onOff » : « on »}

Thanks!

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Claude Gelinas<mailto:notifications@github.com>
Envoyé le :17 avril 2020 21:40
À : claudegel/sinope-130<mailto:sinope-130@noreply.github.com>
Cc : mictechca<mailto:mic_hb@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [claudegel/sinope-130] Impossible to turn on lights (#8)


I also need some info. Could you open Neviweb and with the debug console open, select one of your dimmer and open it. Set the intensity to let say 50% then close the light.
Open the light again and see in the debug console for the parameters if you have this:
XHRPUThttps://neviweb.com/api/device/69458/attribute
JSON
intensity 101
Transmission de la requête
{"intensity":101}

I need to know if intensity is set to 101 to open the dimmer to the same intensity it was before you close it.
his is the way Neviweb GT125 is working and I suppose that GT130 use the same but I can't check it on my side.

**Comment by claudegel** [comment]
Ok I've removed brightness from turn_on. Now it just set onOff to «on» when you turn on the light.
There should be a way to set_intensity  to increase or reduce dimmer intensity. 

Please try to raise intensity of your dimmer with the arrow up in Neviweb and let me know what you see in the debug console. This way it should use intensity like {«intensity» : « xx »} where xx is a number from 0 to 100

Let me know if it work

**Comment by mictechca** [comment]
I guess you made a copy-paste mistake 😊
def turn_on(self, **kwargs):
        """Turn the light on."""
#        brightness_pct = 100
#        if kwargs.get(ATTR_BRIGHTNESS):
#            brightness_pct = \
#                brightness_to_percentage(int(kwargs.get(ATTR_BRIGHTNESS)))
#        if self._is_dimmable:
#            brightness_pct = 101 # Sets the light to last known brightness.
#        self._client.set_brightness(self._id, brightness_pct)
        self._client.set_onOff(self._id, "off")
« off » should be « on » and now turning on will work (tested on my side manually editing the file)
The brightness can’t be set with home assistant at this time, I didn’t debug to know why.
However, I tested on neviweb and here’s me result :
{« intensity » : 20} -> 20 is an integer not a string.
Thanks!

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Claude Gelinas<mailto:notifications@github.com>
Envoyé le :22 avril 2020 20:16
À : claudegel/sinope-130<mailto:sinope-130@noreply.github.com>
Cc : mictechca<mailto:mic_hb@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [claudegel/sinope-130] Impossible to turn on lights (#8)


Ok I've removed brightness from turn_on. Now it just set onOff to «on» when you turn on the light.
There should be a way to set_intensity to increase or reduce dimmer intensity.

Please try to raise intensity of your dimmer with the arrow up in Neviweb and let me know what you see in the debug console. This way it should use intensity like {«intensity» : « xx »} where xx is a number from 0 to 100

Let me know if it work

**Comment by claudegel** [comment]
OK great I've corrected the «off»
Lets try something for the brightness

**Comment by claudegel** [comment]
I've done some modification for the brightness.
please test
Thank you

**Comment by claudegel** [comment]
As-tu testé la nouvelle version. Je veux faire le merge si ca fonctionne

**Comment by mictechca** [comment]
Désolé Claude,

Je viens de la tester et tout est beau. Désolé du délai, je profitais du beau soleil dans mes temps libres.
Tu peux merger, j’ai testé on/off + changement d’intensité.

Merci beaucoup et bonne journée!

De : Claude Gelinas<mailto:notifications@github.com>
Envoyé le :25 avril 2020 09:07
À : claudegel/sinope-130<mailto:sinope-130@noreply.github.com>
Cc : mictechca<mailto:mic_hb@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [claudegel/sinope-130] Impossible to turn on lights (#8)


As-tu testé la nouvelle version. Je veux faire le merge si ca fonctionne

**Comment by claudegel** [comment]
Merci pour l'aide. Profites du soleil. l'été dure pas longtemps au Québec
