### ISSUE TITLE
issue loading component recently

### ISSUE THREAD

**Issue by andrew-wits** [claudegel/sinope-130#92]
Been having some issues as of late after a recent HA restart, the component will no longer load. I verified my credentials are still valid. If I remove the non-required fields in configuration.yaml I get this error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb130/__init__.py", line 106, in setup
    data = Neviweb130Data(hass_config[DOMAIN])
  File "/config/custom_components/neviweb130/__init__.py", line 133, in __init__
    self.neviweb130_client = Neviweb130Client(username, password, network)
  File "/config/custom_components/neviweb130/__init__.py", line 159, in __init__
    self.__get_network()
  File "/config/custom_components/neviweb130/__init__.py", line 208, in __get_network
    self._gateway_id = networks[0]["id"]
KeyError: 0
```

If I add the network field I get this error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb130/__init__.py", line 106, in setup
    data = Neviweb130Data(hass_config[DOMAIN])
  File "/config/custom_components/neviweb130/__init__.py", line 133, in __init__
    self.neviweb130_client = Neviweb130Client(username, password, network)
  File "/config/custom_components/neviweb130/__init__.py", line 159, in __init__
    self.__get_network()
  File "/config/custom_components/neviweb130/__init__.py", line 213, in __get_network
    if network["name"] == self._network_name:
TypeError: string indices must be integers
```

Here's the neviweb130 part of my configuration.yaml (this is how it was before I started modifying it troubleshooting):

```
neviweb130:
  username: '[redacted]'
  password: '[redacted]'
  network: 'home'
  scan_interval: 360
```

I did rename my network in Neviweb's portal from "Home" to "home" just to test as well, not sure if maybe they changed something on their end recently?

**Comment by claudegel** [comment]
I'm on it. Sinopé change its Api login so I have to adjust my code. Now I have neviweb130 back but I'm still working on neviweb custom_component for the fix. I'll post an update today

**Comment by andrew-wits** [comment]
Much appreciated @claudegel

**Comment by claudegel** [comment]
I just release a new version 1.4.5 that fix the problem. Sinopé did some changes in there API
